(function(){
  'use strict';

  var MAIN_API=String(window.TACS_ADMIN_API_URL||'https://script.google.com/macros/s/AKfycbzvhH-x6x8Jbg6_F7nuUn1DaS7A08l97Saq5RpjeoFJsCq6wRdVUyGWBNOiboqTLd3rfQ/exec').trim();
  var NOTICE_API=String(window.POSTO_MATIAS_AVISOS_API_URL||'').trim();
  var DENTAL_API=String(window.DENTAL_AGENDA_API_URL||'').trim();
  var PORTAL_URL='https://merciocamposfar07-hub.github.io/atendimento-acs-farmaceutico/portal-atualizado.html?v=20260728-26&notificacoes=1';
  var UNIT='Unidade de Saúde Posto Matias';
  var AREA='Sítio Japaranduba';
  var AGENT='TACS — Mércio José Campos dos Santos';
  var KEY_STORAGE='tacs-admin-key';

  var DEFAULT_NURSE=[
    {day:'Segunda-feira',service:'Visita',icon:'🏠',available:true},
    {day:'Terça-feira',service:'Pré-natal',icon:'🤰',available:true},
    {day:'Quarta-feira',service:'Folga',icon:'❌',available:false},
    {day:'Quinta-feira',service:'Puericultura - acompanhamento de crianças e adolescentes',icon:'👶',available:true},
    {day:'Sexta-feira',service:'Preventivo',icon:'🌸',available:true}
  ];
  var nurseModel=DEFAULT_NURSE.map(copy),dentalModel=[];

  function byId(id){return document.getElementById(id)}
  function copy(value){return Object.assign({},value)}
  function text(value){return String(value==null?'':value).trim()}
  function escapeHtml(value){return String(value==null?'':value).replace(/[&<>'\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]})}
  function setStatus(id,message,type){var box=byId(id);if(!box)return;box.textContent=message;box.className='status'+(type?' '+type:'')}
  function numberValue(value){var n=Number(value);return Number.isInteger(n)&&n>=0?n:0}
  function isoDate(value){var t=text(value),m=t.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(m)return t;m=t.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?m[3]+'-'+m[2]+'-'+m[1]:''}
  function formatDate(value){var d=isoDate(value);if(!d)return text(value);var p=d.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
  function weekdayName(value){var d=isoDate(value);if(!d)return 'Data inválida';var p=d.split('-').map(Number),date=new Date(Date.UTC(p[0],p[1]-1,p[2]));return ['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'][date.getUTCDay()]}

  function activateTab(id){document.querySelectorAll('.tab').forEach(function(tab){tab.classList.toggle('active',tab.dataset.tab===id)});document.querySelectorAll('.admin-section').forEach(function(section){section.hidden=section.id!==id})}
  document.querySelectorAll('.tab').forEach(function(tab){tab.addEventListener('click',function(){activateTab(tab.dataset.tab)})});

  function getAdminKey(){try{return text(localStorage.getItem(KEY_STORAGE)||sessionStorage.getItem(KEY_STORAGE))}catch(e){return ''}}
  function updateAccessStatus(){var key=getAdminKey();byId('accessStatus').textContent=key?'Chave administrativa salva neste aparelho.':'Nenhuma chave administrativa foi salva neste aparelho.';byId('adminKeyInput').value=key}
  function requireAdminKey(statusId){var key=getAdminKey();if(key)return key;document.querySelector('.access-box').open=true;document.querySelector('.access-box').scrollIntoView({behavior:'smooth',block:'center'});setStatus(statusId,'Para publicar alterações, salve uma vez a chave administrativa deste painel.','warning');return ''}
  byId('saveAdminKey').addEventListener('click',function(){var key=text(byId('adminKeyInput').value);if(key.length<6){byId('accessStatus').textContent='A chave precisa ter pelo menos 6 caracteres.';return}try{localStorage.setItem(KEY_STORAGE,key);sessionStorage.setItem(KEY_STORAGE,key)}catch(e){}updateAccessStatus()});
  byId('clearAdminKey').addEventListener('click',function(){try{localStorage.removeItem(KEY_STORAGE);sessionStorage.removeItem(KEY_STORAGE)}catch(e){}byId('adminKeyInput').value='';updateAccessStatus()});

  function jsonp(api,action,onOk,onFail,extra){if(!api){onFail(new Error('Serviço não configurado.'));return}var cb='tacsAdmin'+Date.now()+Math.floor(Math.random()*99999),script=document.createElement('script'),done=false;var timer=setTimeout(function(){finish(new Error('Tempo esgotado.'))},14000);function finish(error,data){if(done)return;done=true;clearTimeout(timer);delete window[cb];if(script.parentNode)script.remove();error?onFail(error):onOk(data)}window[cb]=function(data){finish(null,data)};script.onerror=function(){finish(new Error('Não foi possível acessar o serviço.'))};var params='action='+encodeURIComponent(action)+'&callback='+encodeURIComponent(cb)+'&v='+Date.now();if(extra)Object.keys(extra).forEach(function(k){params+='&'+encodeURIComponent(k)+'='+encodeURIComponent(extra[k])});script.src=api+(api.indexOf('?')<0?'?':'&')+params;document.head.appendChild(script)}
  function postForm(api,fields,expectedSource,timeoutMs){return new Promise(function(resolve,reject){if(!api){reject(new Error('Serviço não configurado.'));return}var nonce='admin-'+Date.now()+'-'+Math.random().toString(36).slice(2,9),frameName='adminFrame'+Date.now(),iframe=document.createElement('iframe'),form=document.createElement('form'),done=false;var timer=setTimeout(function(){finish(new Error('O serviço demorou para responder.'))},timeoutMs||18000);function cleanup(){clearTimeout(timer);window.removeEventListener('message',receive);if(form.parentNode)form.remove();setTimeout(function(){if(iframe.parentNode)iframe.remove()},200)}function finish(error,data){if(done)return;done=true;cleanup();error?reject(error):resolve(data)}function receive(event){var data=event.data;if(!data||data.nonce!==nonce)return;if(expectedSource&&data.source!==expectedSource)return;data.ok===false?finish(new Error(data.message||'A publicação foi recusada.')):finish(null,data)}function add(name,value){var input=document.createElement('input');input.type='hidden';input.name=name;input.value=String(value==null?'':value);form.appendChild(input)}iframe.name=frameName;iframe.hidden=true;form.method='post';form.action=api;form.target=frameName;form.hidden=true;Object.keys(fields).forEach(function(k){add(k,fields[k])});add('nonce',nonce);window.addEventListener('message',receive);document.body.append(iframe,form);form.submit()})}

  function renderNurse(){var box=byId('nurseDays');box.innerHTML='';nurseModel.forEach(function(item,index){var row=document.createElement('div');row.className='day';row.innerHTML='<strong>'+escapeHtml(item.day)+'</strong><input aria-label="Ícone" maxlength="4" value="'+escapeHtml(item.icon)+'"><input aria-label="Atendimento" value="'+escapeHtml(item.service)+'"><select aria-label="Situação"><option value="true"'+(item.available?' selected':'')+'>Atendimento</option><option value="false"'+(!item.available?' selected':'')+'>Folga / indisponível</option></select><span></span>';var fields=row.querySelectorAll('input,select');fields[0].addEventListener('input',function(){nurseModel[index].icon=this.value});fields[1].addEventListener('input',function(){nurseModel[index].service=this.value});fields[2].addEventListener('change',function(){nurseModel[index].available=this.value==='true'});box.appendChild(row)})}
  function loadNurse(){setStatus('nurseStatus','Carregando a programação atual...');jsonp(MAIN_API,'agenda_enfermeira',function(data){if(data&&data.ok!==false&&Array.isArray(data.dias)&&data.dias.length){nurseModel=data.dias.map(copy);renderNurse();setStatus('nurseStatus','Programação atual carregada.','success')}else{nurseModel=DEFAULT_NURSE.map(copy);renderNurse();setStatus('nurseStatus','A agenda padrão foi exibida porque o serviço não retornou a programação salva.','warning')}},function(){nurseModel=DEFAULT_NURSE.map(copy);renderNurse();setStatus('nurseStatus','Não foi possível conectar ao serviço. A agenda padrão foi exibida temporariamente.','error')})}
  function saveNurse(){var key=requireAdminKey('nurseStatus');if(!key)return;setStatus('nurseStatus','Publicando agenda da enfermeira...');var frame=document.createElement('iframe'),form=document.createElement('form');frame.name='saveNurse'+Date.now();frame.hidden=true;form.method='post';form.action=MAIN_API;form.target=frame.name;form.hidden=true;[['action','salvar_agenda_enfermeira'],['adminKey',key],['payload',JSON.stringify({dias:nurseModel})]].forEach(function(pair){var input=document.createElement('input');input.type='hidden';input.name=pair[0];input.value=pair[1];form.appendChild(input)});document.body.append(frame,form);form.submit();setTimeout(function(){form.remove();frame.remove();loadNurse()},1900)}

  function updateNoticePreview(){var title=text(byId('noticeTitle').value),message=text(byId('noticeMessage').value),priority=byId('noticePriority').value,preview=byId('noticePreview');if(!title&&!message){preview.hidden=true;preview.innerHTML='';return}preview.className='notice-preview'+(priority==='importante'?' important':priority==='urgente'?' urgent':'');preview.innerHTML='<small>'+escapeHtml(byId('noticeType').value)+' • '+escapeHtml(priority)+'</small><strong>'+escapeHtml(title||'Aviso')+'</strong><p>'+escapeHtml(message)+'</p>';preview.hidden=false}
  ['noticeType','noticeTitle','noticeMessage','noticePriority'].forEach(function(id){byId(id).addEventListener(id==='noticeType'||id==='noticePriority'?'change':'input',updateNoticePreview)});
  function fillNotices(data){var medical=data&&data.atendimentoMedico||{},notice=data&&Array.isArray(data.avisos)&&data.avisos[0]||{};byId('medicalStatus').value=medical.situacao||'aguardando';byId('medicalDate').value=medical.data||'';byId('medicalTime').value=medical.horario||'';byId('medicalNote').value=medical.observacao||'';byId('noticePriority').value=notice.prioridade||'informativo';byId('noticeValidity').value=isoDate(notice.validade||'');byId('noticeTitle').value=notice.titulo||'';byId('noticeMessage').value=notice.mensagem||'';var title=(notice.titulo||'').toLowerCase();if(title.indexOf('nutric')>=0)byId('noticeType').value='Atendimento com nutricionista';else if(title.indexOf('vacina')>=0)byId('noticeType').value='Vacinação';else byId('noticeType').value='Aviso geral';updateNoticePreview()}
  function loadNotices(){setStatus('noticeStatus','Carregando os avisos atuais...');jsonp(NOTICE_API,'avisos',function(data){if(data&&data.ok!==false){fillNotices(data);setStatus('noticeStatus','Avisos atuais carregados'+(data.atualizadoEm?' — '+data.atualizadoEm:'')+'.','success')}else setStatus('noticeStatus','O serviço não retornou os avisos atuais.','error')},function(){setStatus('noticeStatus','Não foi possível carregar os avisos atuais.','error')})}
  function noticePayload(){return {action:'publicarAvisos',unidade:UNIT,area:AREA,medicalStatus:byId('medicalStatus').value,medicalDate:text(byId('medicalDate').value),medicalTime:text(byId('medicalTime').value),medicalNote:text(byId('medicalNote').value),priority:byId('noticePriority').value,validity:byId('noticeValidity').value,title:text(byId('noticeTitle').value),message:text(byId('noticeMessage').value)}}
  function publishNotices(){if(!NOTICE_API){setStatus('noticeStatus','Serviço de avisos não configurado.','error');return}var button=byId('publishNotices'),payload=noticePayload();button.disabled=true;setStatus('noticeStatus','Publicando avisos...');fetch(NOTICE_API,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)}).then(function(){setStatus('noticeStatus','Publicação enviada. Conferindo o mural...','warning');setTimeout(function(){button.disabled=false;loadNotices()},1800)}).catch(function(){button.disabled=false;setStatus('noticeStatus','Não foi possível enviar a publicação. Confira a conexão.','error')})}

  function renderDental(){var box=byId('dentalRows');box.innerHTML='';if(!dentalModel.length)setStatus('dentalStatus','A agenda ainda não possui datas. Use “Adicionar outra data”.','warning');dentalModel.forEach(function(item,index){var row=document.createElement('div');row.className='dental-row';row.innerHTML='<label>Data<input type="date" value="'+escapeHtml(isoDate(item.data))+'"></label><label>Dia<input value="'+escapeHtml(item.dia||weekdayName(item.data))+'" readonly></label><label>Vagas comuns<input type="number" inputmode="numeric" min="0" step="1" value="'+numberValue(item.vagasComuns)+'"></label><label>Vagas emergenciais<input type="number" inputmode="numeric" min="0" step="1" value="'+numberValue(item.vagasEmergenciais)+'"></label><button type="button" class="icon-button" aria-label="Remover data">×</button>';var inputs=row.querySelectorAll('input'),remove=row.querySelector('button');inputs[0].addEventListener('change',function(){dentalModel[index].data=this.value;dentalModel[index].dia=weekdayName(this.value);inputs[1].value=dentalModel[index].dia});inputs[2].addEventListener('input',function(){dentalModel[index].vagasComuns=numberValue(this.value)});inputs[3].addEventListener('input',function(){dentalModel[index].vagasEmergenciais=numberValue(this.value)});remove.addEventListener('click',function(){dentalModel.splice(index,1);renderDental()});box.appendChild(row)})}
  function loadDental(){setStatus('dentalStatus','Carregando a agenda odontológica...');jsonp(DENTAL_API,'agenda',function(data){if(data&&data.ok!==false&&Array.isArray(data.dias)){dentalModel=data.dias.map(function(item){return {data:isoDate(item.data),dia:item.dia||weekdayName(item.data),vagasComuns:numberValue(item.vagasComuns),vagasEmergenciais:numberValue(item.vagasEmergenciais)}});renderDental();setStatus('dentalStatus','Agenda odontológica carregada'+(data.atualizadoEm?' — '+data.atualizadoEm:'')+'.','success')}else setStatus('dentalStatus','O serviço não retornou a agenda odontológica.','error')},function(){setStatus('dentalStatus','Não foi possível carregar a agenda odontológica.','error')})}
  function addDentalDate(){var date=dentalModel.length?dentalModel[dentalModel.length-1].data:'';if(date){var d=new Date(date+'T12:00:00');d.setDate(d.getDate()+1);date=d.toISOString().slice(0,10)}else date=new Date(Date.now()+86400000).toISOString().slice(0,10);dentalModel.push({data:date,dia:weekdayName(date),vagasComuns:0,vagasEmergenciais:0});renderDental()}
  function validDentalRows(){if(!dentalModel.length)return 'Adicione pelo menos uma data.';var seen={};for(var i=0;i<dentalModel.length;i++){var item=dentalModel[i],date=isoDate(item.data),weekday=weekdayName(date);if(!date)return 'Há uma data inválida.';if(seen[date])return 'A data '+formatDate(date)+' está repetida.';seen[date]=true;if(['Segunda-feira','Terça-feira','Quinta-feira'].indexOf(weekday)<0)return formatDate(date)+' cai em '+weekday+'. A agenda aceita segunda, terça e quinta.'}return ''}
  function saveDental(){var error=validDentalRows();if(error){setStatus('dentalStatus',error,'error');return}var key=requireAdminKey('dentalStatus');if(!key)return;var button=byId('saveDental');button.disabled=true;setStatus('dentalStatus','Publicando agenda odontológica...');postForm(DENTAL_API,{action:'salvar_agenda',adminKey:key,payload:JSON.stringify({dias:dentalModel})},'agenda-odontologica-tacs',20000).then(function(){setStatus('dentalStatus','Agenda odontológica publicada.','success');return new Promise(function(resolve){setTimeout(resolve,500)})}).then(loadDental).catch(function(error){setStatus('dentalStatus',error.message,'error')}).finally(function(){button.disabled=false})}

  function shareText(message){var url='https://wa.me/?text='+encodeURIComponent(message);window.open(url,'_blank','noopener')}
  function nurseText(){return '📢 *PORTAL TACS – POSTO MATIAS*\n*Agenda da enfermeira*\n\nAgenda semanal da Enfermeira Chefe\n\n'+nurseModel.map(function(item){return item.icon+' *'+item.day+':* '+(item.available?item.service:'Não haverá atendimento')}).join('\n')+'\n\n'+AGENT+'\n'+AREA}
  function medicalText(){return '📢 *PORTAL TACS – POSTO MATIAS*\n*Atendimento médico*\n\nSituação: '+byId('medicalStatus').options[byId('medicalStatus').selectedIndex].text+'\nData: '+text(byId('medicalDate').value||'A confirmar')+'\nHorário: '+text(byId('medicalTime').value||'A confirmar')+'\n'+text(byId('medicalNote').value)+'\n\n'+AGENT+'\n'+AREA}
  function noticeText(){return '📢 *PORTAL TACS – POSTO MATIAS*\n*'+text(byId('noticeTitle').value||byId('noticeType').value)+'*\n\n'+text(byId('noticeMessage').value)+'\n\nValidade: '+formatDate(byId('noticeValidity').value)+'\n'+AGENT+'\n'+AREA}
  function dentalText(){return '📢 *PORTAL TACS – POSTO MATIAS*\n*Agenda odontológica*\n\n'+dentalModel.map(function(item){return '🦷 *'+weekdayName(item.data)+' — '+formatDate(item.data)+'*\nVagas comuns: '+numberValue(item.vagasComuns)+'\nVagas emergenciais: '+numberValue(item.vagasEmergenciais)}).join('\n\n')+'\n\n'+AGENT+'\n'+AREA}
  function customText(){return '📢 *PORTAL TACS – POSTO MATIAS*\n*'+text(byId('customTitle').value||byId('customType').value)+'*\n\n'+text(byId('customMessage').value)+'\nData: '+text(byId('customDate').value)+'\nHorário: '+text(byId('customTime').value)+'\n\n'+AGENT+'\n'+AREA}

  function createShareCard(title,message,meta){var canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1920;var ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,1080,1920);gradient.addColorStop(0,'#031b2d');gradient.addColorStop(1,'#0d5f8a');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1920);ctx.fillStyle='#70e39f';ctx.font='900 46px Arial';ctx.fillText('PORTAL TACS • POSTO MATIAS',70,120);ctx.fillStyle='#fff';ctx.font='900 74px Arial';var y=240;function lines(t,x,max,width,height,font){ctx.font=font;var words=text(t).split(/\s+/),line='',count=0;words.forEach(function(word){var test=line?line+' '+word:word;if(line&&ctx.measureText(test).width>width){if(count<max){ctx.fillText(line,x,y);y+=height;count++}line=word}else line=test});if(line&&count<max){ctx.fillText(line,x,y);y+=height}}lines(title,70,4,940,82,'900 74px Arial');ctx.fillStyle='rgba(255,255,255,.97)';ctx.beginPath();ctx.roundRect(55,y+20,970,1040,42);ctx.fill();y+=120;ctx.fillStyle='#102b3c';lines(message,95,15,890,58,'800 46px Arial');ctx.fillStyle='#fff';ctx.font='900 40px Arial';ctx.fillText(meta||UNIT,70,1700);ctx.fillStyle='#dbe9f1';ctx.font='700 30px Arial';ctx.fillText(AGENT,70,1760);ctx.fillText(AREA,70,1810);return new Promise(function(resolve){canvas.toBlob(function(blob){resolve(new File([blob],'portal-tacs-'+Date.now()+'.png',{type:'image/png'}))},'image/png',1)})}
  function shareCard(title,message,meta){createShareCard(title,message,meta).then(function(file){if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]}))return navigator.share({files:[file],title:title,text:'Portal TACS • Posto Matias'});var url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1200)})}

  byId('saveNurse').addEventListener('click',saveNurse);byId('resetNurse').addEventListener('click',function(){nurseModel=DEFAULT_NURSE.map(copy);renderNurse();setStatus('nurseStatus','Agenda padrão restaurada na tela. Publique para confirmar.','warning')});byId('reloadNurse').addEventListener('click',loadNurse);byId('publishNotices').addEventListener('click',publishNotices);byId('reloadNotices').addEventListener('click',loadNotices);byId('addDentalDate').addEventListener('click',addDentalDate);byId('saveDental').addEventListener('click',saveDental);byId('reloadDental').addEventListener('click',loadDental);byId('clearMedical').addEventListener('click',function(){byId('medicalStatus').value='aguardando';byId('medicalDate').value='';byId('medicalTime').value='';byId('medicalNote').value=''});byId('clearNotice').addEventListener('click',function(){byId('noticeTitle').value='';byId('noticeMessage').value='';byId('noticeValidity').value='';updateNoticePreview()});
  byId('shareNurseText').addEventListener('click',function(){shareText(nurseText())});byId('shareMedicalText').addEventListener('click',function(){shareText(medicalText())});byId('shareNoticeText').addEventListener('click',function(){shareText(noticeText())});byId('shareDentalText').addEventListener('click',function(){shareText(dentalText())});byId('shareCustomText').addEventListener('click',function(){shareText(customText())});
  byId('shareNurseCard').addEventListener('click',function(){shareCard('Agenda da enfermeira',nurseModel.map(function(item){return item.icon+' '+item.day+': '+(item.available?item.service:'Não haverá atendimento')}).join('\n'),UNIT)});byId('shareMedicalCard').addEventListener('click',function(){shareCard('Atendimento médico',medicalText(),UNIT)});byId('shareNoticeCard').addEventListener('click',function(){shareCard(text(byId('noticeTitle').value||'Aviso da Unidade'),text(byId('noticeMessage').value),UNIT)});byId('shareDentalCard').addEventListener('click',function(){shareCard('Agenda odontológica',dentalText(),UNIT)});byId('shareCustomCard').addEventListener('click',function(){shareCard(text(byId('customTitle').value||byId('customType').value),customText(),UNIT)});
  byId('refreshAll').addEventListener('click',function(){loadNurse();loadNotices();loadDental()});
  updateAccessStatus();renderNurse();loadNurse();loadNotices();loadDental();
}());