(function(){
  'use strict';

  var MAIN_API=String(window.TACS_ADMIN_API_URL||'https://script.google.com/macros/s/AKfycbzvhH-x6x8Jbg6_F7nuUn1DaS7A08l97Saq5RpjeoFJsCq6wRdVUyGWBNOiboqTLd3rfQ/exec').trim();
  var NOTICE_API=String(window.POSTO_MATIAS_AVISOS_API_URL||'').trim();
  var DENTAL_API=String(window.DENTAL_AGENDA_API_URL||'').trim();
  var PORTAL_URL='https://merciocamposfar07-hub.github.io/atendimento-acs-farmaceutico/portal-atualizado.html?v=20260728-31&notificacoes=1';
  var UNIT='Unidade de Saúde Posto Matias';
  var AREA='Sítio Japaranduba';
  var AGENT='TACS — Mércio José Campos dos Santos';
  var KEY_STORAGE='tacs-admin-key';

  var DEFAULT_NURSE=[
    {day:'Segunda-feira',service:'Visita',icon:'🏠',available:true},
    {day:'Terça-feira',service:'Pré-natal',icon:'🤰',available:true},
    {day:'Quarta-feira',service:'Folga',icon:'❌',available:false},
    {day:'Quinta-feira',service:'Puericultura - acompanhamento de crianças e adolescentes',icon:'👶',available:true},
    {day:'Sexta-feira',service:'Preventivo',icon:'🌸',available:true}
  ];
  var nurseModel=DEFAULT_NURSE.map(copy),dentalModel=[];

  function byId(id){return document.getElementById(id)}
  function copy(value){return Object.assign({},value)}
  function text(value){return String(value==null?'':value).trim()}
  function escapeHtml(value){return String(value==null?'':value).replace(/[&<>'\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]})}
  function setStatus(id,message,type){var box=byId(id);if(!box)return;box.textContent=message;box.className='status'+(type?' '+type:'')}
  function numberValue(value){var n=Number(value);return Number.isInteger(n)&&n>=0?n:0}
  function isoDate(value){var t=text(value),m=t.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(m)return t;m=t.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?m[3]+'-'+m[2]+'-'+m[1]:''}
  function formatDate(value){var d=isoDate(value);if(!d)return text(value);var p=d.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
  function weekdayName(value){var d=isoDate(value);if(!d)return 'Data inválida';var p=d.split('-').map(Number),date=new Date(Date.UTC(p[0],p[1]-1,p[2]));return ['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'][date.getUTCDay()]}

  function activateTab(id){document.querySelectorAll('.tab').forEach(function(tab){tab.classList.toggle('active',tab.dataset.tab===id)});document.querySelectorAll('.admin-section').forEach(function(section){section.hidden=section.id!==id})}
  document.querySelectorAll('.tab').forEach(function(tab){tab.addEventListener('click',function(){activateTab(tab.dataset.tab)})});

  function getAdminKey(){try{return text(localStorage.getItem(KEY_STORAGE)||sessionStorage.getItem(KEY_STORAGE))}catch(e){return ''}}
  function updateAccessStatus(){var key=getAdminKey();byId('accessStatus').textContent=key?'Chave administrativa salva neste aparelho.':'Nenhuma chave administrativa foi salva neste aparelho.';byId('adminKeyInput').value=key}
  function requireAdminKey(statusId){var key=getAdminKey();if(key)return key;document.querySelector('.access-box').open=true;document.querySelector('.access-box').scrollIntoView({behavior:'smooth',block:'center'});setStatus(statusId,'Para publicar alterações, salve uma vez a chave administrativa deste painel.','warning');return ''}
  byId('saveAdminKey').addEventListener('click',function(){var key=text(byId('adminKeyInput').value);if(key.length<6){byId('accessStatus').textContent='A chave precisa ter pelo menos 6 caracteres.';return}try{localStorage.setItem(KEY_STORAGE,key);sessionStorage.setItem(KEY_STORAGE,key)}catch(e){}updateAccessStatus()});
  byId('clearAdminKey').addEventListener('click',function(){try{localStorage.removeItem(KEY_STORAGE);sessionStorage.removeItem(KEY_STORAGE)}catch(e){}byId('adminKeyInput').value='';updateAccessStatus()});

  function jsonp(api,action,onOk,onFail,extra){if(!api){onFail(new Error('Serviço não configurado.'));return}var cb='tacsAdmin'+Date.now()+Math.floor(Math.random()*99999),script=document.createElement('script'),done=false;var timer=setTimeout(function(){finish(new Error('Tempo esgotado.'))},14000);function finish(error,data){if(done)return;done=true;clearTimeout(timer);delete window[cb];if(script.parentNode)script.remove();error?onFail(error):onOk(data)}window[cb]=function(data){finish(null,data)};script.onerror=function(){finish(new Error('Não foi possível acessar o serviço.'))};var params='action='+encodeURIComponent(action)+'&callback='+encodeURIComponent(cb)+'&v='+Date.now();if(extra)Object.keys(extra).forEach(function(k){params+='&'+encodeURIComponent(k)+'='+encodeURIComponent(extra[k])});script.src=api+(api.indexOf('?')<0?'?':'&')+params;document.head.appendChild(script)}
  function postForm(api,fields,expectedSource,timeoutMs){return new Promise(function(resolve,reject){if(!api){reject(new Error('Serviço não configurado.'));return}var nonce='admin-'+Date.now()+'-'+Math.random().toString(36).slice(2,9),frameName='adminFrame'+Date.now(),iframe=document.createElement('iframe'),form=document.createElement('form'),done=false;var timer=setTimeout(function(){finish(new Error('O serviço não confirmou a publicação. Verifique se a implantação do Apps Script está atualizada.'))},timeoutMs||20000);function cleanup(){clearTimeout(timer);window.removeEventListener('message',receive);if(form.parentNode)form.remove();setTimeout(function(){if(iframe.parentNode)iframe.remove()},200)}function finish(error,data){if(done)return;done=true;cleanup();error?reject(error):resolve(data)}function receive(event){var data=event.data;if(!data||data.nonce!==nonce)return;if(expectedSource&&data.source!==expectedSource)return;data.ok===false?finish(new Error(data.message||'A publicação foi recusada.')):finish(null,data)}function add(name,value){var input=document.createElement('input');input.type='hidden';input.name=name;input.value=String(value==null?'':value);form.appendChild(input)}iframe.name=frameName;iframe.hidden=true;form.method='post';form.action=api;form.target=frameName;form.hidden=true;Object.keys(fields).forEach(function(k){add(k,fields[k])});add('nonce',nonce);window.addEventListener('message',receive);document.body.append(iframe,form);form.submit()})}

  function renderNurse(){var box=byId('nurseDays');box.innerHTML='';nurseModel.forEach(function(item,index){var row=document.createElement('div');row.className='day';row.innerHTML='<strong>'+escapeHtml(item.day)+'</strong><input aria-label="Ícone" maxlength="4" value="'+escapeHtml(item.icon)+'"><input aria-label="Atendimento" value="'+escapeHtml(item.service)+'"><select aria-label="Situação"><option value="true"'+(item.available?' selected':'')+'>Atendimento</option><option value="false"'+(!item.available?' selected':'')+'>Folga / indisponível</option></select><span></span>';var fields=row.querySelectorAll('input,select');fields[0].addEventListener('input',function(){nurseModel[index].icon=this.value});fields[1].addEventListener('input',function(){nurseModel[index].service=this.value});fields[2].addEventListener('change',function(){nurseModel[index].available=this.value==='true'});box.appendChild(row)})}
  function loadNurse(done){setStatus('nurseStatus','Carregando a programação atual...');jsonp(MAIN_API,'agenda_enfermeira',function(data){if(data&&data.ok!==false&&Array.isArray(data.dias)&&data.dias.length){nurseModel=data.dias.map(copy);renderNurse();setStatus('nurseStatus','Programação atual carregada.','success');if(done)done(null,data)}else{nurseModel=DEFAULT_NURSE.map(copy);renderNurse();setStatus('nurseStatus','A agenda padrão foi exibida porque o serviço não retornou a programação salva.','warning');if(done)done(new Error('O serviço não retornou a programação salva.'),data)}},function(error){nurseModel=DEFAULT_NURSE.map(copy);renderNurse();setStatus('nurseStatus','Não foi possível conectar ao serviço. A agenda padrão foi exibida temporariamente.','error');if(done)done(error||new Error('Falha de conexão.'))})}
  function normalizedNurse(list){return (list||[]).map(function(item){return {day:text(item.day),service:text(item.service),icon:text(item.icon),available:!!item.available}})}
  function sameNurse(a,b){return JSON.stringify(normalizedNurse(a))===JSON.stringify(normalizedNurse(b))}
  function saveNurse(){
    var key=requireAdminKey('nurseStatus');if(!key)return;
    var button=byId('saveNurse'),expected=normalizedNurse(nurseModel);
    button.disabled=true;
    setStatus('nurseStatus','Publicando agenda da enfermeira e aguardando confirmação...','warning');
    postForm(MAIN_API,{action:'salvar_agenda_enfermeira',adminKey:key,payload:JSON.stringify({dias:expected})},null,22000)
      .then(function(){
        setStatus('nurseStatus','Publicação recebida. Conferindo os dados salvos...','warning');
        setTimeout(function(){
          loadNurse(function(error,data){
            button.disabled=false;
            if(error){setStatus('nurseStatus','O servidor recebeu a publicação, mas não foi possível confirmar a agenda salva. Atualize a implantação do Apps Script.','error');return}
            if(data&&sameNurse(data.dias,expected))setStatus('nurseStatus','Agenda da enfermeira publicada e confirmada no portal.','success');
            else setStatus('nurseStatus','A agenda retornada pelo servidor é diferente da que foi publicada. A implantação do Apps Script pode estar desatualizada.','error');
          });
        },900);
      })
      .catch(function(error){button.disabled=false;setStatus('nurseStatus',error&&error.message?error.message:'A publicação foi recusada pelo servidor.','error')});
  }

  function updateNoticePreview(){var title=text(byId('noticeTitle').value),message=text(byId('noticeMessage').value),priority=byId('noticePriority').value,preview=byId('noticePreview');if(!title&&!message){preview.hidden=true;preview.innerHTML='';return}preview.className='notice-preview'+(priority==='importante'?' important':priority==='urgente'?' urgent':'');preview.innerHTML='<small>'+escapeHtml(byId('noticeType').value)+' • '+escapeHtml(priority)+'</small><strong>'+escapeHtml(title||'Aviso')+'</strong><p>'+escapeHtml(message)+'</p>';preview.hidden=false}
  ['noticeType','noticeTitle','noticeMessage','noticePriority'].forEach(function(id){byId(id).addEventListener(id==='noticeType'||id==='noticePriority'?'change':'input',updateNoticePreview)});
  function fillNotices(data){var medical=data&&data.atendimentoMedico||{},notice=data&&Array.isArray(data.avisos)&&data.avisos[0]||{};byId('medicalStatus').value=medical.situacao||'aguardando';byId('medicalDate').value=medical.data||'';byId('medicalTime').value=medical.horario||'';byId('medicalNote').value=medical.observacao||'';byId('noticePriority').value=notice.prioridade||'informativo';byId('noticeValidity').value=isoDate(notice.validade||'');byId('noticeTitle').value=notice.titulo||'';byId('noticeMessage').value=notice.mensagem||'';var title=(notice.titulo||'').toLowerCase();if(title.indexOf('nutric')>=0)byId('noticeType').value='Atendimento com nutricionista';else if(title.indexOf('vacina')>=0)byId('noticeType').value='Vacinação';else byId('noticeType').value='Aviso geral';updateNoticePreview()}
  function loadNotices(){setStatus('noticeStatus','Carregando os avisos atuais...');jsonp(NOTICE_API,'avisos',function(data){if(data&&data.ok!==false){fillNotices(data);setStatus('noticeStatus','Avisos atuais carregados'+(data.atualizadoEm?' — '+data.atualizadoEm:'')+'.','success')}else setStatus('noticeStatus','O serviço não retornou os avisos atuais.','error')},function(){setStatus('noticeStatus','Não foi possível carregar os avisos atuais.','error')})}
  function noticePayload(){return {action:'publicarAvisos',unidade:UNIT,area:AREA,medicalStatus:byId('medicalStatus').value,medicalDate:text(byId('medicalDate').value),medicalTime:text(byId('medicalTime').value),medicalNote:text(byId('medicalNote').value),priority:byId('noticePriority').value,validity:byId('noticeValidity').value,title:text(byId('noticeTitle').value),message:text(byId('noticeMessage').value)}}
  function publishNotices(){if(!NOTICE_API){setStatus('noticeStatus','Serviço de avisos não configurado.','error');return}var button=byId('publishNotices'),payload=noticePayload();button.disabled=true;setStatus('noticeStatus','Publicando avisos...');fetch(NOTICE_API,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)}).then(function(){setStatus('noticeStatus','Publicação enviada. Conferindo o mural...','warning');setTimeout(function(){button.disabled=false;loadNotices()},1800)}).catch(function(){button.disabled=false;setStatus('noticeStatus','Não foi possível enviar a publicação. Confira a conexão.','error')})}

  function renderDental(){var box=byId('dentalRows');box.innerHTML='';if(!dentalModel.length)setStatus('dentalStatus','A agenda ainda não possui datas. Use “Adicionar outra data”.','warning');dentalModel.forEach(function(item,index){var row=document.createElement('div');row.className='dental-row';row.innerHTML='<label>Data<input type="date" value="'+escapeHtml(isoDate(item.data))+'"></label><label>Dia<input value="'+escapeHtml(item.dia||weekdayName(item.data))+'" readonly></label><label>Vagas comuns<input type="number" inputmode="numeric" min="0" step="1" value="'+numberValue(item.vagasComuns)+'"></label><label>Vagas emergenciais<input type="number" inputmode="numeric" min="0" step="1" value="'+numberValue(item.vagasEmergenciais)+'"></label><button type="button" class="icon-button" aria-label="Remover data">×</button>';var inputs=row.querySelectorAll('input'),remove=row.querySelector('button');inputs[0].addEventListener('change',function(){dentalModel[index].data=this.value;dentalModel[index].dia=weekdayName(this.value);inputs[1].value=dentalModel[index].dia});inputs[2].addEventListener('input',function(){dentalModel[index].vagasComuns=numberValue(this.value)});inputs[3].addEventListener('input',function(){dentalModel[index].vagasEmergenciais=numberValue(this.value)});remove.addEventListener('click',function(){dentalModel.splice(index,1);renderDental()});box.appendChild(row)})}
  function loadDental(){setStatus('dentalStatus','Carregando a agenda odontológica...');jsonp(DENTAL_API,'agenda',function(data){if(data&&data.ok!==false&&Array.isArray(data.dias)){dentalModel=data.dias.map(function(item){return {data:isoDate(item.data),dia:item.dia||weekdayName(item.data),vagasComuns:numberValue(item.vagasComuns),vagasEmergenciais:numberValue(item.vagasEmergenciais)}});renderDental();setStatus('dentalStatus','Agenda odontológica carregada'+(data.atualizadoEm?' — '+data.atualizadoEm:'')+'.','success')}else setStatus('dentalStatus','O serviço não retornou a agenda odontológica.','error')},function(){setStatus('dentalStatus','Não foi possível carregar a agenda odontológica.','error')})}
  function addDentalDate(){var date=dentalModel.length?dentalModel[dentalModel.length-1].data:'';if(date){var d=new Date(date+'T12:00:00');d.setDate(d.getDate()+1);date=d.toISOString().slice(0,10)}else date=new Date(Date.now()+86400000).toISOString().slice(0,10);dentalModel.push({data:date,dia:weekdayName(date),vagasComuns:0,vagasEmergenciais:0});renderDental()}
  function validDentalRows(){if(!dentalModel.length)return 'Adicione pelo menos uma data.';var seen={};for(var i=0;i<dentalModel.length;i++){var item=dentalModel[i],date=isoDate(item.data),weekday=weekdayName(date);if(!date)return 'Há uma data inválida.';if(seen[date])return 'A data '+formatDate(date)+' está repetida.';seen[date]=true;if(['Segunda-feira','Terça-feira','Quinta-feira'].indexOf(weekday)<0)return formatDate(date)+' cai em '+weekday+'. A odontologia aceita apenas segunda, terça e quinta.'}return ''}
  function saveDental(){var problem=validDentalRows();if(problem){setStatus('dentalStatus',problem,'error');return}var key=requireAdminKey('dentalStatus');if(!key)return;var button=byId('saveDental');button.disabled=true;setStatus('dentalStatus','Publicando agenda odontológica...');postForm(DENTAL_API,{action:'salvar',adminKey:key,payload:JSON.stringify({dias:dentalModel})},'agenda-odontologica-tacs',20000).then(function(data){button.disabled=false;setStatus('dentalStatus',(data&&data.message)||'Agenda odontológica publicada.','success');loadDental()}).catch(function(error){button.disabled=false;setStatus('dentalStatus',error.message||'Não foi possível publicar a agenda.','error')})}

  function nurseText(){var lines=['📢 *PORTAL TACS – POSTO MATIAS*','*Agenda da enfermeira*','','Agenda semanal da Enfermeira Chefe',''];nurseModel.forEach(function(item){lines.push((item.icon||'•')+' *'+item.day+':* '+item.service+(item.available?'':' — indisponível'))});lines.push('','📍 Unidade de Saúde Posto Matias • Sítio Japaranduba','TACS responsável: Mércio José Campos dos Santos');return lines.join('\n')}
  function dentalText(){var lines=['🦷 *PORTAL TACS – POSTO MATIAS*','*Agenda odontológica*',''];dentalModel.forEach(function(item){lines.push('📅 *'+weekdayName(item.data)+' — '+formatDate(item.data)+'*','Vagas comuns: '+numberValue(item.vagasComuns),'Vagas emergenciais: '+numberValue(item.vagasEmergenciais),'')});lines.push('📍 Unidade de Saúde Posto Matias • Sítio Japaranduba');return lines.join('\n')}
  function noticeText(){var lines=['📢 *PORTAL TACS – POSTO MATIAS*',text(byId('noticeType').value),text(byId('noticeTitle').value),text(byId('noticeMessage').value)];if(byId('noticeValidity').value)lines.push('Válido até: '+formatDate(byId('noticeValidity').value));return lines.filter(Boolean).join('\n')}
  function medicalText(){return ['🩺 *PORTAL TACS – POSTO MATIAS*','*Atendimento médico*','Situação: '+byId('medicalStatus').options[byId('medicalStatus').selectedIndex].text,text(byId('medicalDate').value),text(byId('medicalTime').value),text(byId('medicalNote').value),'','📍 Unidade de Saúde Posto Matias • Sítio Japaranduba'].filter(Boolean).join('\n')}
  function customText(){return ['📢 *PORTAL TACS – POSTO MATIAS*',text(byId('customType').value),text(byId('customTitle').value),text(byId('customMessage').value),text(byId('customDate').value),text(byId('customTime').value),'','📍 Unidade de Saúde Posto Matias • Sítio Japaranduba'].filter(Boolean).join('\n')}
  function shareText(content){if(navigator.share){navigator.share({title:'Portal TACS',text:content}).catch(function(){})}else window.open('https://wa.me/?text='+encodeURIComponent(content),'_blank','noopener')}
  function card(title,subtitle,body,fileName){var canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1920;var ctx=canvas.getContext('2d'),g=ctx.createLinearGradient(0,0,1080,1920);g.addColorStop(0,'#041f34');g.addColorStop(.55,'#062c46');g.addColorStop(1,'#0d5f8a');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1920);ctx.fillStyle='#70e39f';ctx.font='900 36px Arial';ctx.fillText('PORTAL TACS • POSTO MATIAS',65,110);ctx.fillStyle='#fff';ctx.font='900 67px Arial';var y=210;wrap(ctx,title,65,y,950,78,4).forEach(function(line){ctx.fillText(line,65,y);y+=78});ctx.fillStyle='rgba(255,255,255,.12)';round(ctx,55,y+15,970,125,30);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 37px Arial';wrap(ctx,subtitle,85,y+70,900,45,2).forEach(function(line){ctx.fillText(line,85,y+70);y+=45});ctx.fillStyle='#fff';round(ctx,50,y+190,980,1120,38);ctx.fill();ctx.fillStyle='#102b3c';ctx.font='750 38px Arial';var bodyY=y+265;wrap(ctx,body,90,bodyY,900,52,18).forEach(function(line){ctx.fillText(line,90,bodyY);bodyY+=52});ctx.fillStyle='rgba(255,255,255,.13)';round(ctx,55,1670,970,150,28);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 34px Arial';ctx.fillText('Unidade de Saúde Posto Matias',85,1735);ctx.font='650 27px Arial';ctx.fillText('Sítio Japaranduba • TACS Mércio José Campos dos Santos',85,1782);canvas.toBlob(function(blob){var file=new File([blob],fileName+'.png',{type:'image/png'});if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]}))navigator.share({files:[file],title:title,text:subtitle}).catch(function(){});else{var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}},'image/png',1)}
  function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
  function wrap(ctx,value,x,y,maxWidth,lineHeight,maxLines){var words=text(value).split(/\s+/),lines=[],line='';words.forEach(function(word){var test=line?line+' '+word:word;if(line&&ctx.measureText(test).width>maxWidth){lines.push(line);line=word}else line=test});if(line)lines.push(line);if(lines.length>maxLines){lines=lines.slice(0,maxLines);lines[maxLines-1]=lines[maxLines-1].replace(/[.,;:!?-]*$/,'')+'…'}return lines}

  byId('saveNurse').addEventListener('click',saveNurse);
  byId('resetNurse').addEventListener('click',function(){nurseModel=DEFAULT_NURSE.map(copy);renderNurse();setStatus('nurseStatus','Agenda padrão restaurada na tela. Toque em publicar para salvar.','warning')});
  byId('reloadNurse').addEventListener('click',function(){loadNurse()});
  byId('publishNotices').addEventListener('click',publishNotices);
  byId('reloadNotices').addEventListener('click',loadNotices);
  byId('clearMedical').addEventListener('click',function(){byId('medicalStatus').value='aguardando';byId('medicalDate').value='';byId('medicalTime').value='';byId('medicalNote').value=''});
  byId('clearNotice').addEventListener('click',function(){byId('noticeTitle').value='';byId('noticeMessage').value='';byId('noticeValidity').value='';updateNoticePreview()});
  byId('addDentalDate').addEventListener('click',addDentalDate);
  byId('saveDental').addEventListener('click',saveDental);
  byId('reloadDental').addEventListener('click',loadDental);
  byId('shareNurseText').addEventListener('click',function(){shareText(nurseText())});
  byId('shareDentalText').addEventListener('click',function(){shareText(dentalText())});
  byId('shareNoticeText').addEventListener('click',function(){shareText(noticeText())});
  byId('shareMedicalText').addEventListener('click',function(){shareText(medicalText())});
  byId('shareCustomText').addEventListener('click',function(){shareText(customText())});
  byId('shareNurseCard').addEventListener('click',function(){card('AGENDA DA ENFERMEIRA','Programação semanal da Enfermeira Chefe',nurseModel.map(function(x){return (x.icon||'•')+' '+x.day+' — '+x.service+(x.available?'':' — indisponível')}).join('\n'),'agenda-enfermeira')});
  byId('shareDentalCard').addEventListener('click',function(){card('AGENDA ODONTOLÓGICA','Datas e vagas disponíveis',dentalModel.map(function(x){return weekdayName(x.data)+' — '+formatDate(x.data)+'\nVagas comuns: '+numberValue(x.vagasComuns)+' • Emergenciais: '+numberValue(x.vagasEmergenciais)}).join('\n\n'),'agenda-odontologica')});
  byId('shareNoticeCard').addEventListener('click',function(){card(text(byId('noticeTitle').value)||'AVISO DA UNIDADE',text(byId('noticeType').value),text(byId('noticeMessage').value),'aviso-posto-matias')});
  byId('shareMedicalCard').addEventListener('click',function(){card('ATENDIMENTO MÉDICO',byId('medicalStatus').options[byId('medicalStatus').selectedIndex].text,[text(byId('medicalDate').value),text(byId('medicalTime').value),text(byId('medicalNote').value)].filter(Boolean).join('\n'),'atendimento-medico')});
  byId('shareCustomCard').addEventListener('click',function(){card(text(byId('customTitle').value)||text(byId('customType').value),text(byId('customType').value),[text(byId('customMessage').value),text(byId('customDate').value),text(byId('customTime').value)].filter(Boolean).join('\n'),'comunicado-portal-tacs')});
  byId('refreshAll').addEventListener('click',function(){loadNurse();loadNotices();loadDental()});

  updateAccessStatus();renderNurse();loadNurse();loadNotices();loadDental();
}());