from pathlib import Path
import sys

p = Path(sys.argv[1] if len(sys.argv) > 1 else 'painel-oficial-agendas-vagas.html')
s = p.read_text(encoding='utf-8')

css_anchor = 'input[type="date"].campo,input[type="time"].campo{display:block;width:100%!important;min-width:0!important;max-width:100%!important;inline-size:100%!important;min-inline-size:0!important;max-inline-size:100%!important;box-sizing:border-box!important}.corpo,.corpo>*{min-width:0}\n'
css_add = '''input[type="date"].campo,input[type="time"].campo{display:block;width:100%!important;min-width:0!important;max-width:100%!important;inline-size:100%!important;min-inline-size:0!important;max-inline-size:100%!important;box-sizing:border-box!important}.corpo,.corpo>*{min-width:0}\n/* AJUSTE_LAYOUT_AGENDAS_PROFISSIONAIS_V1 — aplica o padrão Safari/iPhone já definido no projeto. */\n.cartao .corpo,.cartao .corpo>*{min-width:0!important;max-width:100%!important;box-sizing:border-box!important}\n.cartao .corpo{width:100%!important;overflow:hidden!important}\n.cartao .corpo input.campo,.cartao .corpo textarea.campo,.cartao .corpo select.campo{display:block!important;width:100%!important;max-width:100%!important;min-width:0!important;inline-size:100%!important;min-inline-size:0!important;max-inline-size:100%!important;margin-left:0!important;margin-right:0!important;box-sizing:border-box!important}\n.cartao input[type="date"].campo,.cartao input[type="time"].campo{-webkit-appearance:none!important;appearance:none!important;overflow:hidden!important}\n.cartao input[type="date"].campo::-webkit-date-and-time-value,.cartao input[type="time"].campo::-webkit-date-and-time-value{min-width:0!important;text-align:center}\n.grupoProfissional{width:100%;min-width:0;max-width:100%;border:2px solid #69c7e7;border-radius:24px!important;background:#fff;overflow:hidden;box-shadow:0 8px 18px rgba(7,58,85,.14)}\n.grupoProfissional>summary{list-style:none;display:flex;align-items:center;justify-content:space-between;gap:12px;width:100%;min-width:0;padding:15px 16px;background:linear-gradient(145deg,var(--petroleo),var(--petroleo2));color:#fff;cursor:pointer;touch-action:manipulation}\n.grupoProfissional>summary::-webkit-details-marker{display:none}\n.grupoProfissionalTitulo{display:flex;align-items:center;gap:11px;min-width:0;flex:1}\n.grupoProfissionalTitulo .icone{flex:0 0 auto}\n.grupoProfissionalNome{min-width:0}\n.grupoProfissionalNome strong{display:block;color:#fff;font-size:1.16rem;line-height:1.15;overflow-wrap:anywhere}\n.grupoProfissionalMeta{display:block;margin-top:4px;color:#d8eef7;font-size:.88rem;font-weight:750;line-height:1.25}\n.grupoAcao{display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto;min-height:42px;max-width:42%;padding:8px 11px;border:2px solid #8ad8f1;border-radius:999px;background:#fff;color:var(--petroleo);font-size:.82rem;font-weight:900;line-height:1.05;text-align:center}\n.grupoProfissional[open] .grupoAbrir,.grupoProfissional:not([open]) .grupoFechar{display:none}\n.agendaProfissionalCorpo{display:grid;grid-template-columns:minmax(0,1fr);gap:12px;width:100%;min-width:0;max-width:100%;padding:12px;background:#eaf2f6}\n.agendaProfissionalCorpo>.cartao{width:100%;min-width:0;max-width:100%}\n@media(max-width:560px){.grupoProfissional>summary{align-items:flex-start;padding:14px}.grupoAcao{max-width:38%;font-size:.76rem;padding:8px 9px}.agendaProfissionalCorpo{padding:10px}}\n'''
if css_anchor not in s:
    raise SystemExit('Âncora CSS não encontrada; nenhuma alteração aplicada.')
s = s.replace(css_anchor, css_add, 1)

render_anchor = 'function render(){var filtroProf=document.getElementById(\'filtroProf\').value,filtroDia=document.getElementById(\'filtroDia\').value;'
if render_anchor not in s:
    raise SystemExit('Função render não encontrada; nenhuma alteração aplicada.')

helper = '''function agruparAgendasPorProfissional(alvo,lista){\n  if(!alvo||!Array.isArray(lista)||!lista.length)return;\n  var grupos={},ordem=[];\n  lista.forEach(function(a){\n    var modulo=normalId(a.MODULO);\n    if(!grupos[modulo]){var p=prof(a.MODULO)||{};grupos[modulo]={p:p,registros:[]};ordem.push(modulo)}\n    grupos[modulo].registros.push(a);\n  });\n  var fragmento=document.createDocumentFragment();\n  ordem.forEach(function(modulo){\n    var grupo=grupos[modulo],p=grupo.p||{},registros=grupo.registros;\n    var totalVagas=registros.reduce(function(t,a){return t+num(a.VAGAS_COMUNS)+num(a.VAGAS_EMERGENCIAIS)},0);\n    var diasAtivos=registros.filter(function(a){return bool(a.ATIVO)}).length;\n    var bloco=document.createElement('details');bloco.className='grupoProfissional';bloco.dataset.modulo=modulo;\n    var resumo=document.createElement('summary');\n    resumo.innerHTML='<div class="grupoProfissionalTitulo"><span class="icone">'+esc(p.ICONE||'📅')+'</span><div class="grupoProfissionalNome"><strong>'+esc(p.TITULO_PUBLICO||p.NOME||txt(registros[0].MODULO).trim())+'</strong><span class="grupoProfissionalMeta">'+registros.length+' dia(s) na semana • '+diasAtivos+' ativo(s) • '+totalVagas+' vaga(s)</span></div></div><span class="grupoAcao"><span class="grupoAbrir">Abrir agenda</span><span class="grupoFechar">Fechar agenda</span></span>';\n    bloco.appendChild(resumo);\n    var corpo=document.createElement('div');corpo.className='agendaProfissionalCorpo';\n    registros.forEach(function(a){var seletor='details[data-chave="'+CSS.escape(chave(a))+'"]';var cartao=alvo.querySelector(seletor);if(cartao)corpo.appendChild(cartao)});\n    bloco.appendChild(corpo);fragmento.appendChild(bloco);\n  });\n  alvo.innerHTML='';alvo.appendChild(fragmento);\n}\n'''
s = s.replace(render_anchor, helper + render_anchor, 1)

needle = "lista.forEach(function(a){var c=alvo.querySelector('details[data-chave=\"'+CSS.escape(chave(a))+'\"]');if(c){var s=c.querySelector('[name=\"situacao\"]');if(s)s.value=normalSituacao(a.SITUACAO)}})}document.getElementById('qAgendas')"
replacement = "lista.forEach(function(a){var c=alvo.querySelector('details[data-chave=\"'+CSS.escape(chave(a))+'\"]');if(c){var s=c.querySelector('[name=\"situacao\"]');if(s)s.value=normalSituacao(a.SITUACAO)}});agruparAgendasPorProfissional(alvo,lista)}document.getElementById('qAgendas')"
if needle not in s:
    raise SystemExit('Ponto de agrupamento não encontrado; nenhuma alteração aplicada.')
s = s.replace(needle, replacement, 1)

p.write_text(s, encoding='utf-8')
print('AJUSTE_LAYOUT_AGENDAS_PROFISSIONAIS_V1_OK')
