const fs=require('fs');const vm=require('vm');const assert=require('assert');
const backend=fs.readFileSync('apps-script/ZZZZ_22_SaudeNotificacoesV1.gs','utf8');
const front=fs.readFileSync('portal-notification-health.js','utf8');
const agenda=fs.readFileSync('agenda-enfermeira.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const panel=fs.readFileSync('teste-v1/painel-recados-campanhas-v1.html','utf8');
const official=fs.readFileSync('painel-oficial-recados-campanhas.html','utf8');
const builder=fs.readFileSync('scripts/build_apps_script_release.js','utf8');
assert(backend.includes("VERSAO:'1.1.1'"));
assert(backend.includes("REGISTRY_SHEET:'TACS_NOTIFICACOES_DISPOSITIVOS'"));
assert(backend.includes("REPAIR_TARGET_SHEET:'TACS_REPAROS_NOTIFICACOES_ALVOS'"));
assert(backend.includes("'SUBSCRIPTION_ID','AREA_ID','ID_PORTAL','ONESIGNAL_ID'"));
assert(!backend.match(/REGISTRY_HEADERS[\s\S]{0,500}'CPF'/));assert(!backend.match(/REGISTRY_HEADERS[\s\S]{0,500}'CNS'/));assert(!backend.match(/REGISTRY_HEADERS[\s\S]{0,500}'CELULAR'/));
assert(backend.includes("saudeNotificacoesV1ResolverMoradorOpcional_"));
assert(backend.includes("if(!cpf&&!cns)return {idPortal:''}"));
assert(backend.includes("if(!idPortal)idPortal=saudeNotificacoesV1Texto_(sheet.getRange(linha,3).getDisplayValue())"));
assert(backend.includes("if(c.status!=='ATIVO')alvos.push"));
assert(backend.includes("saudeNotificacoesV1ReparoPendenteSubscription_"));
assert(front.includes("if(!oneSignal)return Promise.resolve(null)"));
assert(!front.includes("if(!currentResident||!oneSignal)"));
assert(front.includes("if(validDocument(doc))payload.documento=doc"));
assert(front.includes("mode:'no-cors'"));
assert(front.includes("repair.textContent='🔧 Reparar agora'"));
assert(front.includes("tacs:notificacao-reparo-concluido"));
assert(!front.includes('localStorage.setItem')&&!front.includes('sessionStorage.setItem'));
assert(agenda.includes("document.dispatchEvent(new CustomEvent('tacs:notificacao-reparo-concluido'"));
assert(index.includes('portal-notification-health.js?v=20260813-notif-health-v106'));
assert(panel.includes('Saúde das notificações'));assert(panel.includes('Solicitar reparo das notificações da área'));assert(panel.includes("post('admin_notificacoes_saude'"));assert(panel.includes("post('admin_notificacoes_solicitar_reparo_area'"));
assert(!panel.includes('SUBSCRIPTION_ID</'));assert(official.includes('20260813-notif-health-v106'));assert(builder.includes("marker: 'TACS_SAUDE_NOTIFICACOES_V1'"));
const context={Object:Object,Number:Number,String:String,Boolean:Boolean,Array:Array,Date:Date,JSON:JSON,Math:Math,RegExp:RegExp,Error:Error,console:console,moradoresAdminV1Digitos_:function(v){return String(v==null?'':v).replace(/\D/g,'')}};vm.createContext(context);vm.runInContext(backend,context);
let x=context.saudeNotificacoesV1ClassificarExport_({invalid_identifier:'f',notification_types:'1'},false);assert.equal(x.status,'ATIVO');
x=context.saudeNotificacoesV1ClassificarExport_({invalid_identifier:'t',notification_types:'-2'},false);assert.equal(x.status,'INATIVO');
x=context.saudeNotificacoesV1ClassificarExport_({invalid_identifier:'f',notification_types:'1'},true);assert.equal(x.status,'REPARO');
x=context.saudeNotificacoesV1ResolverMoradorOpcional_('', 'JAPARANDUBA');assert.equal(x.idPortal,'');
console.log('Saúde das notificações v1.1.1: check-in anônimo, vínculo preservado e reparo seletivo validados.');
