'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(ROOT,'apps-script','ZZZZ_35_CampanhasAutomaticasV1.gs'),'utf8');
const ctx=vm.createContext({console,Date,JSON,Math});
vm.runInContext(src,ctx);
const catalog=JSON.parse(JSON.stringify(ctx.campanhasAutomaticasV1Catalogo_()));
assert.equal(catalog.length,18);
const aug=catalog.filter(x=>x.mes===8);
assert.equal(aug.length,2);
assert.deepEqual(aug.map(x=>x.tema),['lilas','dourado']);
const plan=JSON.parse(JSON.stringify(ctx.campanhasAutomaticasV1PlanejarAno_('JAPARANDUBA',2026)));
const augPlan=plan.filter(x=>x.MES==='08');
assert.equal(augPlan.length,2);
assert.ok(augPlan.every(x=>x.INICIO==='2026-08-01'&&x.VALIDADE==='2026-08-31'));
const leap=JSON.parse(JSON.stringify(ctx.campanhasAutomaticasV1PlanejarAno_('JAPARANDUBA',2028))).find(x=>x.MES==='02');
assert.equal(leap.VALIDADE,'2028-02-29');
const publicBackend=fs.readFileSync(path.join(ROOT,'apps-script','ZZ_12_PublicoAgendasPortalV1.gs'),'utf8');
assert.match(publicBackend,/publicoAgendasV1LerCampanhas_/);
assert.match(publicBackend,/campanhas: campanhas/);
const renderer=fs.readFileSync(path.join(ROOT,'portal-controle-integral.js'),'utf8');
for(const c of ['campaign-theme-lilas','campaign-theme-dourado','campaign-description','integral-campaign'])assert.ok(renderer.includes(c));
const panel=fs.readFileSync(path.join(ROOT,'painel-oficial-recados-campanhas.html'),'utf8');
assert.match(panel,/admin_publicacoes_dados/);
const period=fs.readFileSync(path.join(ROOT,'campanhas-periodo-v2.js'),'utf8');
assert.match(period,/Cor da campanha/);
assert.match(period,/camp-theme-lilas/);
const build=fs.readFileSync(path.join(ROOT,'scripts','build_apps_script_release.js'),'utf8');
assert.match(build,/ZZZZ_35_CampanhasAutomaticasV1\.gs/);
const cron=fs.readFileSync(path.join(ROOT,'.github','workflows','campanhas-automaticas-diarias.yml'),'utf8');
assert.match(cron,/campanhas_automaticas_executar/);
assert.match(cron,/cron: '5 3 \* \* \*'/);
console.log('Campanhas automáticas V1: calendário, cores, vigência, renderer e rotina diária validados.');
