'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const dental=read('portal-odontologia-segunda-sexta.js'),config=read('agenda-config.js'),index=read('index.html'),backend=read('apps-script/ZZZZ_36_CorrecaoDataOdontologiaV1.gs'),card=read('portal-ajustes-finais.js');

assert.match(dental,/function reserveViaJsonp\(item\)/);
assert.match(dental,/action=reservar_get&areaId=/);
assert.match(dental,/&callback=' \+ encodeURIComponent\(callbackName\)/);
assert.match(dental,/reserveViaJsonp\(item\)\.then/);
assert.match(dental,/var shouldDisable = !formReady\(\) \|\| !selection\.confirmed/);
assert.match(dental,/Boolean\(selection && selection\.confirmed && formReady\(\)\)/);
assert.doesNotMatch(dental,/saveSlotsCache\(\);\s*queueDurableReservation\(item\);/);
assert.match(backend,/action==='reservar_get'/);
assert.match(backend,/VERSAO:'2\.2\.0'/);
assert.match(backend,/var restantes=disponiveis-1;/);
assert.match(backend,/setValue\(restantes\)/);
assert.match(backend,/SpreadsheetApp\.flush\(\)/);
assert.match(config,/DENTAL_AGENDA_API_URL/);
assert.match(card,/current\.confirmed/);
assert.match(index,/portal-odontologia-segunda-sexta\.js\?v=20260817-dental-reserva-jsonp-v107/);
console.log('DENTAL_RESERVA_JSONP_V107_OK');
