'use strict';
const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('recados-campanhas-whatsapp-card-v9.js','utf8');
assert.match(src,/c\.width=1080;c\.height=1920/,'card deve continuar 1080x1920');
assert.match(src,/RECADO DO TACS/,'recado deve identificar autoria TACS');
assert.doesNotMatch(src,/RECADO DA UNIDADE/,'recado nao pode continuar identificado como da unidade');
assert.match(src,/Mércio José Campos dos Santos/,'deve haver fallback de autoria do TACS');
assert.match(src,/portal-tacs-oficial-card\.jpg/,'deve usar o simbolo oficial do Portal TACS ja existente no projeto');
assert.match(src,/PORTAL TACS/,'rodape deve manter Portal TACS');
assert.match(src,/data\.title/,'titulo precisa continuar dinamico');
assert.match(src,/data\.message/,'mensagem precisa continuar dinamica');
assert.match(src,/data\.priority/,'prioridade precisa continuar dinamica');
assert.match(src,/data\.validity/,'validade precisa continuar dinamica');
assert.match(src,/function drawCampaign\(data\)/,'renderer separado de campanhas deve continuar existente');
const recado=src.slice(src.indexOf('function draw(data)'),src.indexOf('function normalizeTheme'));
assert.doesNotMatch(recado,/conecta/i,'renderer de recado nao pode usar ativos do Conecta Saude Comunitaria');
assert.match(recado,/#0f3046|#102d40/,'texto principal deve usar contraste escuro forte');
console.log('WHATSAPP_RECADO_VISUAL_TACS_V1_OK');
