'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const html=read('central-administrativa-tacs.html');
const js=read('central-administrativa-tacs.js');
const manifest=JSON.parse(read('manifest-central-admin.webmanifest'));
assert.equal(manifest.name,'Central Administrativa TACS');
assert.match(manifest.start_url,/central-administrativa-tacs\.html$/);
assert.equal(manifest.display,'standalone');
assert.match(html,/CENTRAL ADMINISTRATIVA TACS/);
assert.match(html,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
assert.match(html,/Saúde das notificações/);
assert.match(html,/data-module="moradores"/);
assert.match(html,/data-module="recados"/);
assert.match(html,/data-permission="MORADORES_LER"/);
assert.match(html,/data-permission="PUBLICACOES_GERENCIAR"/);
assert.match(html,/data-module="agendas" data-admin-only="true"/);
assert.match(html,/data-module="profissionais" data-admin-only="true"/);
assert.match(html,/id="viewerBack"/);
assert.match(js,/portalTacsAdminTokenV1/);
assert.match(js,/portalTacsTerritorioTokenV1/);
assert.match(js,/admin_territorio_login_tacs/);
assert.match(js,/admin_territorio_dados/);
assert.match(js,/admin_notificacoes_saude/);
assert.match(js,/painel-oficial-recados-campanhas\.html\?area=/);
assert.match(js,/teste-v1\/painel-moradores-v2\.html/);
assert.match(js,/filter\(function\(a\)\{return a&&a\.ativa!==false\}\)/);
assert.match(js,/post\('admin_moradores_status'[\s\S]*post\('admin_notificacoes_saude'/,
  'Saúde de moradores deve terminar antes da consulta autenticada das notificações.');
assert.doesNotMatch(js,/subscriptionId\s*[:=]\s*['"][0-9a-f-]{20,}/i);
console.log('Central Administrativa TACS: um ícone, sessão territorial, permissões e Saúde Geral validados.');
