'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const backend=read('apps-script/ZZZZ_43_IdentificacaoFamiliarPublicaV1.gs');
const selection=read('apps-script/ZZZZ_44_SelecaoMembroFamiliaPublicaV1.gs');
const frontend=read('portal-identificacao-familia-v1.js');
const loader=read('portal-auto-update.js');
const build=read('scripts/build_apps_script_release.js');
new vm.Script(backend,{filename:'ZZZZ_43_IdentificacaoFamiliarPublicaV1.gs'});
new vm.Script(selection,{filename:'ZZZZ_44_SelecaoMembroFamiliaPublicaV1.gs'});
new vm.Script(frontend,{filename:'portal-identificacao-familia-v1.js'});
assert.match(backend,/publico_familia_consultar/);
assert.match(backend,/identificacaoFamiliarPublicaV1NormalizarFamilia_/);
assert.match(backend,/documentoConfirmacao/);
assert.match(backend,/requerConfirmacao:true/);
assert.match(backend,/identificacaoFamiliarPublicaV1Membros_/);
assert.match(backend,/vinculoFamiliarNotifV1Ler_/);
assert.match(selection,/publico_familia_membro/);
assert.match(selection,/documentoAcesso/);
assert.match(selection,/CacheService/);
assert.match(frontend,/data-family-search/);
assert.match(frontend,/data-family-confirm/);
assert.match(frontend,/data-member-token/);
assert.match(frontend,/publico_familia_consultar/);
assert.match(frontend,/publico_familia_membro/);
assert.match(frontend,/Salvar .* neste cadastro/);
assert.match(frontend,/O Portal só preenche campo vazio/);
assert.match(frontend,/documentoLocalizador/);
assert.match(frontend,/documentoNovo/);
assert.match(frontend,/pendingMissing=''[^;]*;pendingType=''/,'Ao entrar no fluxo familiar, documento não localizado anterior não pode ser reaproveitado em outro integrante.');
assert.match(frontend,/OneSignalDeferred/,'A consulta pode aproveitar o vínculo familiar do aparelho sem alterar o Push.');

assert.match(loader,/portal-identificacao-familia-v1\.js\?v=[^\"']+/,'O carregador familiar precisa ter cache-buster explícito.');
assert.match(loader,/isAdminPage\(\)\|\|document\.getElementById/,'A nova camada não deve ser carregada nos painéis administrativos.');
assert.match(build,/ZZZZ_43_IdentificacaoFamiliarPublicaV1\.gs/);
assert.match(build,/TACS_IDENTIFICACAO_FAMILIAR_PUBLICA_V1/);
assert.match(build,/ZZZZ_44_SelecaoMembroFamiliaPublicaV1\.gs/);
assert.match(build,/TACS_SELECAO_MEMBRO_FAMILIA_PUBLICA_V1/);

console.log('Identificação familiar pública V1: 02/002, 34/034, isolamento, seleção segura e complemento documental validados.');
