const fs=require('fs');
const assert=require('assert');

function read(path){return fs.readFileSync(path,'utf8');}
const central=read('central-administrativa-tacs.html');
const centralJs=read('central-administrativa-tacs.js');
const unified=read('conecta-acesso-unificado-v1.js');
const resident=read('conecta-morador-session-v1.js');
const backend=read('apps-script/ZZZZ_51_AcessoUnificadoConectaV1.gs');
const territoryBackend=read('apps-script/ZZZZ_17_TacsAreasAdminV1.gs');
const agendasBackend=read('apps-script/ZZZZ_28_AgendasProfissionaisTerritoriaisV1.gs');
const moradoresBackend=read('apps-script/ZZZZ_15_MoradoresAdminPortalV1.gs');
const publicacoesBackend=read('apps-script/ZZZZ_20_PublicacoesTerritoriaisV1.gs');
const suporteBackend=read('apps-script/ZZZZ_48_SuporteMoradoresV1.gs');
const moduleCore=read('conecta-module-core-v1.js');
const health=read('apps-script/ZZZZ_22_SaudeNotificacoesV1.gs');
const support=read('painel-suporte-moradores-v2.html');
const areas=read('teste-v1/painel-tacs-areas-v1.js');
const areasHtml=read('teste-v1/painel-tacs-areas-v1.html');
const build=read('scripts/build_apps_script_release.js');

new Function(centralJs);
new Function(unified);
new Function(resident);
new Function(backend);
new Function(areas);
new Function(moduleCore);

assert(central.includes('conecta-acesso-unificado-v1.js'),'A Central deve carregar a entrada unificada');
assert(unified.includes("b.id='tabMorador'"),'Entrada unificada deve oferecer perfil Morador');
assert(unified.includes("b.id='tabUbs'"),'Entrada unificada deve oferecer perfil UBS');
assert(unified.includes("function loginUbsAccess()"),'UBS deve possuir entrada única por PIN');
assert(!unified.includes("cscUbsCpf"),'Tela UBS não deve pedir CPF nem credencial adicional');
assert(!unified.includes("Primeiro acesso da UBS"),'Tela de primeiro acesso UBS não deve reaparecer');
assert(backend.includes("function conectaAcessoV1UbsPorPin_"),'Backend deve identificar a UBS diretamente pelo PIN cadastrado');
assert(backend.includes("conecta_ubs_login_pin"),'Backend unificado deve aceitar UBS por PIN tanto em computador novo quanto reconhecido');
assert(unified.includes("id=\"cscUbsOpenPanels\""),'UBS localizada deve virar um cartão clicável para abrir os painéis');
assert(unified.includes("function openUbsPanels(r)"),'Resultado da UBS deve possuir navegação própria para os painéis');
assert(unified.includes("ConectaCentralUbsV1.entrar"),'Clique da UBS deve entregar a sessão autenticada à Central sem novo login');
assert(centralJs.includes("UBS_TOKEN_KEY='portalConectaUbsTokenV1'"),'Central deve reconhecer a sessão própria da UBS');
assert(centralJs.includes("window.ConectaCentralUbsV1={entrar:entrarPaineisUbs}"),'Central deve expor a entrada cirúrgica dos painéis da UBS');
assert(centralJs.includes("r.perfil==='UBS'?'ubs':'admin'"),'Contexto devolvido como UBS deve manter o modo UBS, sem virar Administrador');
assert(moduleCore.includes("var UBS_TOKEN_KEY='portalConectaUbsTokenV1'"),'Núcleo dos painéis deve transportar a sessão UBS');
assert(moduleCore.includes("out.ubsToken=s.ubsToken"),'Requisições dos painéis devem enviar o token UBS ao backend');
assert(backend.includes("function conectaAcessoV1ValidarSessaoUbs_"),'Backend deve validar a sessão UBS antes de liberar os painéis');
assert(backend.includes("'conecta_ubs_encerrar'"),'Sessão UBS deve poder ser encerrada sem afetar outros perfis');
assert(territoryBackend.includes("var ubs=conectaAcessoV1ValidarSessaoUbs_(p,true)"),'Validador territorial deve aceitar sessão UBS no escopo da própria unidade');
assert(territoryBackend.includes("ubsAtual:ubsAtual?tacsTerritorioV1PublicarTacs_(ubsAtual):null"),'Contexto da Central deve publicar a UBS autenticada');
assert(agendasBackend.includes("if(acesso.perfil==='TACS'){")&&agendasBackend.includes("else if(acesso.perfil==='UBS'){"),'Agendas e profissionais devem aceitar UBS sem alterar a blindagem própria do TACS');
assert(moradoresBackend.includes("var ubs=conectaAcessoV1ValidarSessaoUbs_(p,true)"),'Moradores deve validar sessão UBS');
assert(publicacoesBackend.includes("acesso.perfil==='TACS'||acesso.perfil==='UBS'"),'Recados e campanhas devem respeitar permissões da UBS');
assert(suporteBackend.includes("acesso.perfil==='TACS'||acesso.perfil==='UBS'"),'Suporte aos moradores deve respeitar permissões da UBS');
assert(central.includes('data-module="ubs" data-admin-only="true"'),'Central do Administrador deve ter módulo próprio de UBS');
assert(centralJs.includes('function showAdminUbs('),'Administrador deve receber lista das UBS cadastradas sem credencial da unidade');
assert(centralJs.includes('Apenas visualizar')&&centralJs.includes('data-ubs-mode="edit"'),'Gestão remota da UBS deve separar visualizar e editar');
assert(territoryBackend.includes("'UBS'"),'Cadastro territorial deve aceitar o perfil UBS isolado');
assert(territoryBackend.includes("'FUNCAO_UBS'"),'Cadastro UBS deve persistir a função do responsável');
assert(unified.includes("p.textContent='Esqueci meu PIN'"),'Tela de acesso deve oferecer Esqueci meu PIN');
assert(unified.includes("fastPin=/(?:login_pin|criar_pin)$/.test(action)"),'Morador deve usar confirmação rápida para login/criação de PIN');
assert(unified.includes("wait=fastPin?450:650"),'Fallback remoto do Morador deve consultar o PIN em cadência curta sem saturar o servidor');
assert(unified.includes("function aquecerPinMorador()"),'Morador deve aquecer o backend ao digitar o PIN');
assert(/conecta-acesso-unificado-v1\.js\?v=[A-Za-z0-9._-]+/.test(central),'Acesso unificado deve carregar com revisão explícita para invalidar cache');
assert(unified.includes("currentRecoveryRole"),'Recuperação deve respeitar o perfil escolhido');
assert(unified.includes("chaveConfianca:proof"),'Recuperação deve enviar prova do aparelho');
assert(!/SMS|WhatsApp OTP|c[oó]digo SMS/i.test(unified),'Recuperação não deve depender de SMS');

assert(backend.includes("TRUST_SHEET:'TACS_CONECTA_APARELHOS_CONFIAVEIS'"),'Backend deve persistir somente prova hash de aparelho confiável');
assert(backend.includes("conecta_recuperacao_registrar_aparelho"),'Backend deve registrar aparelho confiável após autenticação');
assert(backend.includes("dispositivoHash:conectaAcessoV1Hash_(dispositivo)"),'Recuperação deve ficar vinculada ao mesmo aparelho');
assert(backend.includes("recupere o PIN em um aparelho já reconhecido"),'Admin/TACS não podem redefinir PIN só conhecendo CPF');
assert(backend.includes("recupere o PIN no aparelho já reconhecido por este morador"),'Morador não pode redefinir PIN só conhecendo CPF');
assert(backend.includes("function conectaAcessoV1SalvarCpf_"),'Primeiro acesso deve poder qualificar o cadastro existente com CPF');
assert(unified.includes("state.cpfNaoLocalizado=r.ambiguo!==true"),'CPF ausente no banco deve marcar o ramo de confirmação por nascimento sem alterar o fluxo de CPF já cadastrado.');
assert(unified.includes("setStatus('CPF reconhecido no cadastro.','ok');renderPinCreate()"),'CPF já cadastrado deve seguir direto para criação do PIN sem pedir nascimento.');
assert(unified.includes("Confira seus dados antes de continuar"),'CPF ausente confirmado por nascimento deve abrir uma revisão antes da gravação.');
assert(unified.includes('id="cscResidentCpfReviewCorrect"')&&unified.includes('>Corrigir</button>'),'Revisão deve oferecer botão Corrigir.');
assert(unified.includes("Pare um momento e confira os 11 números do CPF e a data de nascimento antes de salvar."),'A interface deve chamar atenção para conferir CPF e nascimento antes da gravação.');
assert(unified.includes("confirmarCpf:'SIM'"),'A gravação do CPF deve acontecer somente após confirmação explícita da revisão.');
assert(backend.includes("revisao.revisarCpf=true"),'Backend deve devolver etapa de revisão sem gravar imediatamente o CPF ausente.');
assert(backend.includes("function conectaAcessoV1ConfirmarCpfRevisado_"),'Backend deve confirmar novamente a identidade antes de gravar o CPF revisado.');
assert(backend.includes("if(!atual)conectaAcessoV1SalvarCpf_(item,cpf);"),'CPF revisado deve ser salvo automaticamente somente em campo vazio.');
assert(backend.includes("conectaAcessoV1Cpf_(p.cpf||identidade.cpf)"),'CPF revisado deve passar novamente pela validação canônica de 11 dígitos e CPF válido.');
assert(unified.includes("Agora crie o seu PIN com quatro números."),'Após CPF confirmado/salvo, a próxima etapa deve ser a criação explícita do PIN de quatro números.');
assert(unified.includes("Confirmar PIN de 4 números"),'A criação do PIN deve exigir confirmação do mesmo PIN de quatro números.');
assert(backend.includes("CPF_PREENCHIDO_EM_CAMPO_VAZIO"),'CPF deve ser escrito no registro canônico quando o campo estiver vazio');
assert(backend.includes("Cadastro pendente de conferência. Você pode continuar normalmente com sua solicitação."),'Morador sem correspondência segura não pode ser bloqueado');
assert(backend.includes("function conectaAcessoV1ContarPendenciasArea_"),'Pendências cadastrais devem alimentar a Central');
assert(backend.includes("O PIN deve ter exatamente 4 números."),'PIN do morador deve ter quatro números');
assert(build.includes("apps-script/ZZZZ_51_AcessoUnificadoConectaV1.gs"),'Módulo unificado deve entrar no release Apps Script');

assert(resident.includes('Esta etapa é obrigatória.'),'Notificações devem ser obrigatórias no primeiro acesso');
assert(!/Agora n[aã]o/i.test(resident),'Gate inicial não deve oferecer pular notificações');
assert(resident.includes("conecta_morador_notificacao_confirmar"),'Ativação precisa ser confirmada no backend');
assert(resident.includes("renderFamily"),'Sessão autenticada deve apresentar núcleo familiar');
assert(backend.includes("familia:familia"),'Sessão de Morador autenticada por PIN deve devolver a família vinculada ao cadastro.');
assert(resident.includes('Quem precisa do atendimento?'),'Após o PIN, o Portal deve apresentar os integrantes da família para seleção.');
assert(resident.includes("portalConectaMoradorTokenV1"),'Próximos acessos devem usar sessão do morador');
assert(resident.includes('hasBackgroundRequest()'),'Morador deve poder abrir o snapshot local enquanto uma nova sessão é confirmada');
assert(resident.includes("if(!token){showPortalToast('Acesso aberto. Aguarde a confirmação segura do servidor"),'Alterações do morador devem esperar token remoto novo');

assert(centralJs.includes('LOGOFF_IMEDIATO_V4'),'Logoff atual deve preservar dados locais e retornar imediatamente ao login');
assert(centralJs.includes('LOGOFF_IMEDIATO_V4'),'Logoff deve responder no primeiro toque sem esperar o servidor');
assert(centralJs.includes('cancelarOperacaoAtivaSemCallback'),'Logoff deve cancelar transporte pendente para evitar disputa de interface');
assert(centralJs.includes("sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(TERRITORY_TOKEN_KEY)"),'Logoff deve preservar cache local removendo apenas credenciais remotas da sessão');
assert(centralJs.includes("if(hasSession&&payload)try{invalidarSessaoServidorEmSegundoPlano(action,payload)}catch(e){}"),'Logoff deve invalidar a sessão remota em segundo plano sem bloquear a interface');
assert(centralJs.includes('PIN_LOCAL_SEM_TOKEN_V3'),'PIN local deve abrir somente contexto confirmado, nunca um token remoto persistido');
assert(!centralJs.includes('token:bearer'),'Cofre local administrativo não pode receber token do servidor');
assert(centralJs.includes("abrirAcessoLocal('admin',pin)")&&centralJs.includes("abrirAcessoLocal('tacs',pin)"),'Administrador e TACS devem tentar o PIN local antes do servidor');
assert(central.includes('conecta-pin-local-v2.js'),'Central deve carregar o cofre local cifrado');
assert(central.includes('conecta-morador-pin-local-v2.js'),'Central deve carregar o desbloqueio local do Morador');
assert(central.includes('touch-action:manipulation!important'),'Botão Logoff deve usar toque direto no iPhone');
assert(centralJs.includes("sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(TERRITORY_TOKEN_KEY)"),'Logoff deve remover somente tokens de autenticação');
assert(!/sessionStorage\.clear\(|localStorage\.clear\(/.test(centralJs),'Logoff não pode apagar armazenamento inteiro');
assert(centralJs.includes('LOGIN_PREFETCH_ESTATICO_V2'),'Login deve aquecer recursos sem bloquear o carregamento inicial');
assert(centralJs.includes("window.addEventListener('load'"),'Pré-carga deve começar depois do primeiro load ou por interação no PIN');
assert(centralJs.includes("fetch(url+'?v=20260910-login-prefetch-v2'"),'Pré-carga deve usar fetch assíncrono/cache');
assert(centralJs.includes('TAREFA_10_SHELL_PERSISTENTE_V1'),'Central deve usar o shell persistente aprovado na Tarefa 10');
assert(!centralJs.includes("location.assign(url+sep+'from=central&_cb='+Date.now());"),'Agendas não deve abandonar a Central após a Tarefa 10');
assert(centralJs.includes("painel-oficial-agendas-vagas.html?area="),'Agendas e Vagas deve manter a rota canônica dentro do shell');
assert(centralJs.includes('ensureShellFrame(name,url,title')&&centralJs.includes('showShellFrame(name,frame,title'),'Agendas e demais módulos devem abrir pela mesma sessão/shell');
assert(!centralJs.includes("link.rel='prefetch'"),'Não voltar ao prefetch que mantém o Safari carregando');

assert(health.includes('REPAIR_VALID_HOURS:24'),'Solicitação de reparo deve expirar em 24 horas');
assert(health.includes('autoNoPrimeiroAcesso'), 'Reparo expirado com vínculo deve poder ser automático no primeiro acesso');
assert(health.includes('if(expirado&&!vinculado)return null'),'Sem vínculo válido, reparo expirado deve liberar nova ação administrativa');

assert(support.includes("diagFilter=''"),'Diagnóstico não deve abrir mostrando automaticamente a lista de aptos');
assert(support.includes("data-diag-filter"),'Indicadores do diagnóstico devem ser clicáveis');
assert(support.includes("if(!diagFilter)")&&support.includes("details.classList.add('hidden')"),'Detalhes devem ficar ocultos até selecionar indicador');

assert(areasHtml.includes('id="areaLinkState"'),'Formulário de área deve expor estado real do vínculo');
assert(areasHtml.includes('id="saveAreaButton"'),'Botão de vínculo deve ter estado controlável');
assert(areas.includes("✓ Área vinculada e ativa"),'Área ativa já vinculada deve aparecer como confirmada');
assert(areas.includes("Salvar novo vínculo"),'Mudança real de vínculo deve habilitar Salvar novo vínculo');
assert(areas.includes("Vínculo confirmado:"),'Confirmação deve informar área/unidade vinculadas');

assert(central.includes('portalTacsCentralContextCacheV3:'),'Perfil deve ler o cache V3 usado pela Central');
assert(central.includes('ctx.administradores'),'Perfil deve listar administradores reais retornados pelo servidor');
assert(central.includes('Plataforma institucional de saúde comunitária.'),'Rodapé deve usar assinatura institucional final');
assert(!/2026\/2027/.test(central),'Rodapé não pode ter 2026/2027');
assert(central.includes('plataforma de gestão e acesso à saúde comunitária'),'Login deve explicar claramente o que é o Conecta');
assert(central.includes('acessível pelo celular'),'Login deve explicitar o acesso pelo celular');
assert(central.includes('Proposta do Conecta Saúde Comunitária'),'Título institucional da proposta deve permanecer no acesso.');
assert(!central.includes('Porque o Conecta Saúde Comunitária foi desenvolvido'),'Título antigo não deve reaparecer no acesso.');
assert(!central.includes('Entre como administrador ou TACS da sua área.'),'Aviso antigo circulado em verde deve permanecer removido.');
assert(central.includes('class="csc-login-purpose-card"'),'Texto da proposta deve permanecer dentro do card institucional.');
assert(central.includes('LOGIN_PROPOSTA_APP4_2026_09_11_V1'),'A proposta deve usar a skin App4 oficial da tela de acesso.');
assert(!central.includes('<small>Tecnologia para tornar o acesso à saúde comunitária mais simples, organizado e acessível.</small>'),'A assinatura institucional não deve reaparecer duplicada no bloco de acesso.');

console.log('Conecta acesso unificado e correções pendentes: OK');
