const fs=require('fs');const vm=require('vm');const assert=require('assert');
const backend=fs.readFileSync('apps-script/ZZZZ_22_SaudeNotificacoesV1.gs','utf8');
const delivery=fs.readFileSync('apps-script/ZZZZ_19_NotificacoesSegmentadasV1.gs','utf8');
const front=fs.readFileSync('portal-notification-health.js','utf8');
const agenda=fs.readFileSync('agenda-enfermeira.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const panel=fs.readFileSync('teste-v1/painel-recados-campanhas-v1.html','utf8');
const official=fs.readFileSync('painel-oficial-recados-campanhas.html','utf8');
const warm=fs.readFileSync('admin-warmup.js','utf8');
const receiptPage=fs.readFileSync('confirmar-recebimento.html','utf8');
const builder=fs.readFileSync('scripts/build_apps_script_release.js','utf8');
assert(backend.includes("VERSAO:'1.1.2'"));
assert(backend.includes("REGISTRY_SHEET:'TACS_NOTIFICACOES_DISPOSITIVOS'"));
assert(backend.includes("REPAIR_TARGET_SHEET:'TACS_REPAROS_NOTIFICACOES_ALVOS'"));
assert(backend.includes("'SUBSCRIPTION_ID','AREA_ID','ID_PORTAL','ONESIGNAL_ID'"));
assert(!backend.match(/REGISTRY_HEADERS[\s\S]{0,500}'CPF'/));assert(!backend.match(/REGISTRY_HEADERS[\s\S]{0,500}'CNS'/));assert(!backend.match(/REGISTRY_HEADERS[\s\S]{0,500}'CELULAR'/));
assert(backend.includes("saudeNotificacoesV1ResolverMoradorOpcional_"));
assert(backend.includes("if(!cpf&&!cns)return {idPortal:''}"));
assert(backend.includes("if(!idPortal)idPortal=saudeNotificacoesV1Texto_(sheet.getRange(linha,3).getDisplayValue())"));
assert(backend.includes("if(c.status!=='ATIVO')alvos.push"));
assert(backend.includes("saudeNotificacoesV1ReparoPendenteSubscription_"));
assert(backend.includes("admin_notificacoes_solicitar_reparo_aparelho"));
assert(backend.includes("function saudeNotificacoesV1SolicitarReparoAparelho_"));
assert(backend.includes("subscriptionRef||p.referencia||p.ref"));
assert(backend.includes("if(classificacao.status==='ATIVO')"));
assert(backend.includes("Nenhum reparo foi solicitado"));
assert(backend.includes("Reparo solicitado somente para este aparelho. Os demais aparelhos não foram alterados."));
assert(delivery.includes("TRACKING_VERSION:'1.1.0'"));
assert(delivery.includes("OPEN_SHEET:'TACS_NOTIFICACOES_ABERTURAS'"));
assert(delivery.includes("RECEIPT_SHEET:'TACS_NOTIFICACOES_COMPROVANTES'"));
assert(delivery.includes("admin_notificacao_resultado"));
assert(delivery.includes("publico_notificacao_aberta"));
assert(delivery.includes("publico_notificacao_webhook"));
assert(delivery.includes("publico_confirmar_recebimento"));
assert(delivery.includes("include_subscription_ids:[item.alvo.subscriptionId]"));
assert(delivery.includes("text:'Confirmar recebimento'"));
assert(delivery.includes("url:'_osp=do_not_open'"));
assert(delivery.includes("confirmacaoToken:item.token"));
assert(delivery.includes("estado==='CONFIRMADO'"));
assert(delivery.includes("estado==='EXIBIDO_TECNICO'"));
assert(delivery.includes("function notificacoesAreaV1ResultadoPublicacao_"));
assert(delivery.includes("function notificacoesAreaV1Metricas_"));
assert(delivery.includes("successful"));
assert(delivery.includes("received"));
assert(delivery.includes("converted"));
assert(delivery.includes("nunca trata aceitação pelo serviço Push como recebimento"));
assert(front.includes("if(!oneSignal)return Promise.resolve(null)"));
assert(!front.includes("if(!currentResident||!oneSignal)"));
assert(front.includes("if(validDocument(doc))payload.documento=doc"));
assert(front.includes("mode:'no-cors'"));
assert(front.includes("repair.textContent='🔧 Reparar agora'"));
assert(front.includes("tacs:notificacao-reparo-concluido"));
assert(front.includes("Notifications.addEventListener('click',registerNotificationOpen)"));
assert(front.includes("publico_notificacao_aberta"));
assert(front.includes("data.referenciaId"));
assert(!front.includes('familyDeviceNotice'));
assert(!front.includes('showFamilyContext'));
assert(!front.includes('localStorage.setItem')&&!front.includes('sessionStorage.setItem'));
assert(agenda.includes("document.dispatchEvent(new CustomEvent('tacs:notificacao-reparo-concluido'"));
assert(agenda.includes("'notification.willDisplay'"));assert(agenda.includes("'notification.clicked'"));
assert(agenda.includes("API + '?action=publico_notificacao_webhook'"));
assert(/agenda-enfermeira\.js\?v=[^"']+/.test(index));
assert(panel.includes('Saúde das notificações'));assert(panel.includes('Solicitar reparo das notificações da área'));assert(panel.includes("post('admin_notificacoes_saude'"));assert(panel.includes("post('admin_notificacoes_solicitar_reparo_area'"));
assert(!fs.existsSync('painel-oficial-saude-notificacoes.html'));
assert(warm.includes("/\\/painel-oficial-recados-campanhas\\.html$/"));
assert(warm.includes("admin_notificacoes_solicitar_reparo_aparelho"));
assert(warm.includes("if(!ref||estado==='ATIVO')return"));
assert(warm.includes("🔧 Solicitar reparo deste aparelho"));
assert(warm.includes("✓ Reparo já solicitado para este aparelho"));
assert(warm.includes("payload.subscriptionRef=ref"));
assert(!warm.includes('payload.subscriptionId='));
assert(warm.includes("admin_notificacao_resultado"));
assert(warm.includes("📊 Ver entrega desta notificação"));
assert(warm.includes("Recebimento comprovado"));
assert(warm.includes("Confirmados pelo morador"));
assert(warm.includes("Aguardando comprovação"));
assert(!warm.includes("Aceitos pelo serviço Push"));
assert(receiptPage.includes("Confirmando recebimento…"));
assert(receiptPage.includes("Recebimento confirmado. Você já pode fechar esta página."));
assert(receiptPage.includes("publico_confirmar_recebimento"));
assert(!panel.includes('SUBSCRIPTION_ID</'));
assert(official.includes('Saúde das notificações'));
assert(official.includes('admin_notificacoes_saude'));
assert(builder.includes("marker: 'TACS_SAUDE_NOTIFICACOES_V1'"));
const context={Object:Object,Number:Number,String:String,Boolean:Boolean,Array:Array,Date:Date,JSON:JSON,Math:Math,RegExp:RegExp,Error:Error,console:console,moradoresAdminV1Digitos_:function(v){return String(v==null?'':v).replace(/\D/g,'')}};vm.createContext(context);vm.runInContext(delivery,context);vm.runInContext(backend,context);
let metrics=context.notificacoesAreaV1Metricas_({successful:17,received:12,failed:2,errored:1,converted:7,remaining:0});assert.equal(metrics.aceitos,17);assert.equal(metrics.confirmados,12);assert.equal(metrics.canceladas,2);assert.equal(metrics.falhas,1);assert.equal(metrics.cliques,7);assert.equal(metrics.tentativas,20);
let x=context.saudeNotificacoesV1ClassificarExport_({invalid_identifier:'f',notification_types:'1'},false);assert.equal(x.status,'ATIVO');
x=context.saudeNotificacoesV1ClassificarExport_({invalid_identifier:'t',notification_types:'-2'},false);assert.equal(x.status,'INATIVO');
x=context.saudeNotificacoesV1ClassificarExport_({invalid_identifier:'f',notification_types:'1'},true);assert.equal(x.status,'REPARO');
x=context.saudeNotificacoesV1ResolverMoradorOpcional_('', 'JAPARANDUBA');assert.equal(x.idPortal,'');
assert.equal(context.saudeNotificacoesV1NormalizarRef_('ABCDEF12'),'abcdef12');
assert.throws(function(){context.saudeNotificacoesV1NormalizarRef_('123')},/Referência técnica/);
console.log('Saúde das notificações consolidada em Recados e campanhas: vínculo, reparo e métricas validados.');