'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..');
function read(p){return fs.readFileSync(path.join(ROOT,p),'utf8')}
const backend=read('apps-script/ZZZZ_40_MensagensIndividuaisMoradorV1.gs');
const frontend=read('teste-v1/mensagem-individual-morador-v1.js');
const panel=read('teste-v1/painel-moradores-v2.html');
const transport=read('teste-v1/painel-moradores-transport-v2.js');
new vm.Script(backend,{filename:'ZZZZ_40_MensagensIndividuaisMoradorV1.gs'});
new vm.Script(frontend,{filename:'mensagem-individual-morador-v1.js'});
assert.match(backend,/admin_mensagem_individual_buscar/);
assert.match(backend,/admin_mensagem_individual_enviar/);
assert.match(backend,/admin_mensagem_individual_status/);
assert.match(backend,/TACS_NOTIFICACOES_FAMILIAS|TACS_VINCULO_FAMILIAR_NOTIF_V1/);
assert.match(backend,/mapa\[id\]!==morador\.familiaId/,'O destinatário precisa ser filtrado pela família vinculada no servidor.');
assert.match(backend,/notificacoesAreaV1PrepararComprovantes_/);
assert.match(backend,/notificacoesAreaV1AplicarRespostasEnvio_/);
assert.match(backend,/RECEIPT_SHEET/);
assert.match(backend,/OPEN_SHEET/);
assert.doesNotMatch(frontend,/subscriptionId|subscription_id|include_subscription_ids/i,'A interface não pode expor identificadores técnicos de Push.');
assert.match(frontend,/Confirmar atendimento/);
assert.match(frontend,/Alterar data/);
assert.match(frontend,/Lembrete/);
assert.match(frontend,/Cancelamento/);
assert.match(frontend,/Outra mensagem/);
assert.match(frontend,/Exibida no aparelho/);
assert.match(frontend,/Aberta/);
assert.match(frontend,/Recebimento confirmado/);
assert.match(panel,/cadastro familiar/i,'A busca deve informar que aceita cadastro familiar.');
assert.match(panel,/mensagem-individual-morador-v1\.js\?v=/,'O painel deve carregar o módulo isolado de mensagem individual.');
assert.match(transport,/PortalTacsMensagemIndividual\.abrir\(item\)/,'Cada resultado individual precisa oferecer o envio de mensagem.');
assert.match(transport,/admin_mensagem_individual_buscar/,'A busca por número familiar deve usar a verificação exata no servidor.');
assert.match(transport,/^\(function\(\)\{/);
console.log('Mensagem individual por morador V1: contrato estático aprovado.');
