'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const dental=read('portal-odontologia-segunda-sexta.js'),config=read('agenda-config.js'),index=read('index.html'),admin=read('painel-oficial-agendas-vagas.html'),backend=read('apps-script/ZZZZ_36_CorrecaoDataOdontologiaV1.gs'),card=read('portal-ajustes-finais.js');
assert.match(dental,/var pending = !selection\.confirmed;/);
assert.match(dental,/var shouldDisable = !formReady\(\) \|\| pending;/);
assert.match(dental,/send\.dataset\.dentalReservationPending = '1'/);
assert.match(dental,/if \(!selection\.confirmed \|\| !formReady\(\)\) \{ refreshSend\(\); return; \}/);
assert.doesNotMatch(dental,/serverCount\s*<=\s*item\.optimisticRemaining/);
assert.match(dental,/function verifyReservation[\s\S]*postReservation\(item\)\.then/);
assert.doesNotMatch(dental,/atualização da planilha está demorando, mas o envio pelo WhatsApp já está liberado/);
assert.match(config,/dentalReservationPending === '1'[\s\S]*send\.disabled = true/);
assert.match(index,/portal-odontologia-segunda-sexta\.js\?v=20260817-dental-whatsapp-bridge-v2/);
assert.match(dental,/selecao: function \(\)/);
assert.match(dental,/prontoParaEnvio: function \(\)/);
assert.match(dental,/formularioValido: function \(\)/);
assert.match(card,/function waitForCurrentDentalReservation\(requestId\)/);
assert.match(card,/api\.formularioValido/);

assert.match(card,/function currentDentalSelection\(\)/);
assert.doesNotMatch(card,/if \(dental\.reservedOnSelection\)/);
assert.match(card,/api\.formularioValido/);
assert.match(card,/dental && dental\.confirmed && dental\.requestId/);
assert.match(dental,/portalTacsDentalAgendaV103FullWeek/);
assert.match(dental,/ALLOWED_DAYS\.indexOf\(day\) === -1\) return null/);
assert.match(admin,/Hora de expiração da agenda/);
assert.match(admin,/name="encerraHorario" type="time"/);
assert.match(backend,/VERSAO:'2\.0\.0'/);
assert.match(backend,/Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira'/);
console.log('DENTAL_CONFIRMATION_GATE_V103_OK');
