'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const ROOT=path.resolve(__dirname,'..');function read(p){return fs.readFileSync(path.join(ROOT,p),'utf8')}
const backend=read('apps-script/ZZZZ_40_MensagensIndividuaisMoradorV1.gs'),familyBackend=read('apps-script/ZZZZ_41_MensagensFamiliaV1.gs'),frontend=read('teste-v1/mensagem-individual-morador-v1.js'),familyFrontend=read('teste-v1/mensagem-familia-v1.js'),integration=read('teste-v1/mensagem-individual-morador-integracao-v1.js'),panel=read('teste-v1/painel-moradores-v2.html'),transport=read('teste-v1/painel-moradores-transport-v2.js');
[backend,familyBackend,frontend,familyFrontend,integration].forEach((s,i)=>new vm.Script(s,{filename:'mensagem-'+i+'.js'}));
assert.match(backend,/admin_mensagem_individual_buscar/);assert.match(backend,/admin_mensagem_individual_enviar/);assert.match(backend,/admin_mensagem_individual_status/);assert.match(backend,/mapa\[id\]!==morador\.familiaId/);assert.match(backend,/notificacoesAreaV1PrepararComprovantes_/);assert.match(backend,/RECEIPT_SHEET/);assert.match(backend,/OPEN_SHEET/);
assert.doesNotMatch(frontend,/subscriptionId|subscription_id|include_subscription_ids/i);assert.doesNotMatch(integration,/subscriptionId|subscription_id|include_subscription_ids/i);assert.doesNotMatch(familyFrontend,/subscriptionId|subscription_id|include_subscription_ids/i);
assert.match(frontend,/Confirmar atendimento/);assert.match(frontend,/Exibida no aparelho/);assert.match(frontend,/Recebimento confirmado/);assert.match(panel,/mensagem-individual-morador-v1\.js\?v=/);assert.match(panel,/mensagem-individual-morador-integracao-v1\.js\?v=/);
assert.match(integration,/familiaQuery/);assert.match(integration,/aplicarFamiliaExata/);assert.match(integration,/card\.remove\(\)/,'A busca por família deve remover resultados estranhos devolvidos pela busca genérica.');assert.match(integration,/Enviar mensagem para toda a família/);assert.match(integration,/Enviar mensagem individual/);assert.match(integration,/mensagem-familia-v1\.js/);assert.match(integration,/002, 072/);assert.match(integration,/admin_mensagem_individual_buscar/);assert.match(integration,/PortalTacsMensagemIndividual/);assert.match(integration,/MutationObserver/);
assert.match(familyBackend,/TACS_MENSAGEM_FAMILIA_V1/);assert.match(familyBackend,/admin_mensagem_familia_enviar/);assert.match(familyBackend,/mapa\[sid\]!==familia/,'O envio geral deve permanecer restrito à família selecionada.');assert.match(familyBackend,/notificacoesAreaV1PrepararComprovantes_/);assert.match(familyBackend,/notificacoesAreaV1AplicarRespostasEnvio_/);assert.match(familyFrontend,/PortalTacsMensagemFamilia/);assert.match(familyFrontend,/Enviar para esta família/);
assert.match(transport,/admin_moradores_buscar/);assert.doesNotMatch(transport,/admin_mensagem_individual_buscar/);assert.doesNotMatch(transport,/PortalTacsMensagemIndividual/);
console.log('Mensagens por morador/família: busca exata e contratos estáticos aprovados.');
