const fs=require('fs');const vm=require('vm');const assert=require('assert');
const backend=fs.readFileSync('apps-script/ZZZZ_22_SaudeNotificacoesV1.gs','utf8');
const front=fs.readFileSync('portal-notification-health.js','utf8');
const agenda=fs.readFileSync('agenda-enfermeira.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const panel=fs.readFileSync('teste-v1/painel-recados-campanhas-v1.html','utf8');
const official=fs.readFileSync('painel-oficial-recados-campanhas.html','utf8');
const builder=fs.readFileSync('scripts/build_apps_script_release.js','utf8');
assert(backend.includes("var TACS_SAUDE_NOTIFICACOES_V1 = Object.freeze"));
assert(backend.includes("REGISTRY_SHEET:'TACS_NOTIFICACOES_DISPOSITIVOS'"));
assert(backend.includes("'SUBSCRIPTION_ID','AREA_ID','ID_PORTAL','ONESIGNAL_ID'"));
assert(!backend.match(/REGISTRY_HEADERS[\\s\\S]{0,500}'CPF'/));assert(!backend.match(/REGISTRY_HEADERS[\\s\\S]{0,500}'CNS'/));assert(!backend.match(/REGISTRY_HEADERS[\\s\\S]{0,500}'CELULAR'/));
assert(backend.includes("action==='publico_notificacao_checkin'"));assert(backend.includes("action==='admin_notificacoes_saude'"));assert(backend.includes("admin_notificacoes_solicitar_reparo_area"));
assert(backend.includes("/subscriptions/'+encodeURIComponent(subscriptionId)+'/user/identity"));assert(backend.includes("/users/by/onesignal_id/"));
assert(front.includes("add('action','publico_notificacao_checkin')"));assert(front.includes("add('documento'" )===false);assert(front.includes("documento:doc"));assert(!front.includes('localStorage.setItem')&&!front.includes('sessionStorage.setItem'));
assert(front.includes("repair.textContent='🔧 Reparar agora'"));assert(front.includes("tacs:notificacao-reparo-concluido"));
assert(agenda.includes("document.dispatchEvent(new CustomEvent('tacs:notificacao-reparo-concluido'"));
assert(index.includes('portal-notification-health.js?v=20260813-notif-health-v106'));
assert(panel.includes('Saúde das notificações'));assert(panel.includes('Solicitar reparo das notificações da área'));assert(panel.includes("post('admin_notificacoes_saude'"));assert(panel.includes("post('admin_notificacoes_solicitar_reparo_area'"));
assert(!panel.includes('SUBSCRIPTION_ID</'));assert(official.includes('20260813-notif-health-v106'));assert(builder.includes("marker: 'TACS_SAUDE_NOTIFICACOES_V1'"));
const context={Object:Object,Number:Number,String:String,Boolean:Boolean,Array:Array,Date:Date,JSON:JSON,Math:Math,RegExp:RegExp,Error:Error,console:console};vm.createContext(context);vm.runInContext(backend,context);
let x=context.saudeNotificacoesV1Classificar_({permission:true,optedIn:true,tokenAtivo:true,areaConfirmada:true,ultimoCheckin:'2026-08-13 08:00:00'}, {enabled:true,notification_types:1}, false);assert.equal(x.status,'ATIVO');
x=context.saudeNotificacoesV1Classificar_({permission:true,optedIn:true,tokenAtivo:true,areaConfirmada:true,ultimoCheckin:'2026-08-13 08:00:00'}, {enabled:false,notification_types:-2}, false);assert.equal(x.status,'INATIVO');
x=context.saudeNotificacoesV1Classificar_({permission:true,optedIn:true,tokenAtivo:true,areaConfirmada:true,ultimoCheckin:'2026-08-13 08:00:00'}, {enabled:true,notification_types:1}, true);assert.equal(x.status,'REPARO');
x=context.saudeNotificacoesV1Classificar_({permission:false,optedIn:false,tokenAtivo:false,areaConfirmada:false,ultimoCheckin:'2026-08-13 08:00:00'}, null, false);assert.equal(x.status,'REPARO');
console.log('Saúde das notificações: vínculo interno, isolamento, estados e reparo administrativo validados.');
