/** Portal TACS — mensagens por cadastro familiar V1.0.0 */
var TACS_MENSAGEM_FAMILIA_V1=Object.freeze({VERSAO:'1.0.0',RESULT_PREFIX:'tacs_msg_familia_v1_result_',RESULT_SECONDS:300});
var mensagemFamiliaV1DoGetAnterior_,mensagemFamiliaV1DoPostAnterior_;
(function(){if(typeof doGet==='function'){mensagemFamiliaV1DoGetAnterior_=doGet;doGet=function(e){return mensagemFamiliaV1Get_(e)||mensagemFamiliaV1DoGetAnterior_(e)}}if(typeof doPost==='function'){mensagemFamiliaV1DoPostAnterior_=doPost;doPost=function(e){return mensagemFamiliaV1Post_(e)||mensagemFamiliaV1DoPostAnterior_(e)}}})();
function mensagemFamiliaV1Texto_(v){return String(v==null?'':v).trim()}function mensagemFamiliaV1Guardar_(id,r){CacheService.getScriptCache().put(TACS_MENSAGEM_FAMILIA_V1.RESULT_PREFIX+id,JSON.stringify(r),300)}function mensagemFamiliaV1Ler_(id){var s=CacheService.getScriptCache().get(TACS_MENSAGEM_FAMILIA_V1.RESULT_PREFIX+id);if(!s)return null;try{return JSON.parse(s)}catch(e){return null}}
function mensagemFamiliaV1Json_(o,cb){var j=JSON.stringify(o),c=mensagemFamiliaV1Texto_(cb);return ContentService.createTextOutput(c&&/^[A-Za-z_$][\w$.]{0,100}$/.test(c)?c+'('+j+');':j).setMimeType(c?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON)}
function mensagemFamiliaV1Get_(e){var p=e&&e.parameter?e.parameter:{};if(mensagemFamiliaV1Texto_(p.action).toLowerCase()!=='admin_mensagem_familia_result')return null;var id=mensagemFamiliaV1Texto_(p.requestId),r=mensagemFamiliaV1Ler_(id);return mensagemFamiliaV1Json_(r?{ok:true,pendente:false,result:r}:{ok:true,pendente:true},p.callback)}
function mensagemFamiliaV1Post_(e){var p=e&&e.parameter?e.parameter:{},a=mensagemFamiliaV1Texto_(p.action).toLowerCase();if(['admin_mensagem_familia_enviar','admin_mensagem_familia_status'].indexOf(a)<0)return null;var id=mensagemFamiliaV1Texto_(p.requestId),r;try{if(!/^[A-Za-z0-9_-]{8,160}$/.test(id))throw new Error('Identificador inválido.');var s=mensagemIndividualV1Contexto_(p,a==='admin_mensagem_familia_enviar');r=a==='admin_mensagem_familia_enviar'?mensagemFamiliaV1Enviar_(p,s.contexto,s.acesso,id):mensagemFamiliaV1Status_(p,s.contexto)}catch(err){r={ok:false,message:err&&err.message?err.message:String(err)}}mensagemFamiliaV1Guardar_(id,r);return mensagemIndividualV1ResponderPost_(id,r)}
function mensagemFamiliaV1Alvos_(contexto,familia,cfg){var mapa=mensagemIndividualV1MapaFamilias_(tacsTerritorioV1Planilha_(),contexto.areaId),vistos={};return notificacoesAreaV1AlvosAtivos_(cfg.appId,cfg.apiKey,contexto,notificacoesAreaV1QuantidadeAreas_()).filter(function(a){var sid=mensagemFamiliaV1Texto_(a&&a.subscriptionId).toLowerCase();if(!sid||vistos[sid]||mapa[sid]!==familia)return false;vistos[sid]=true;return true}).map(function(a){return {subscriptionId:a.subscriptionId,idPortal:'FAMILIA_'+familia,tipoAparelho:a.tipoAparelho,navegador:a.navegador,sistema:a.sistema}})}
function mensagemFamiliaV1Enviar_(p,contexto,acesso,id){var familia=mensagemIndividualV1NormalizarFamilia_(p.familiaId||''),msg=mensagemFamiliaV1Texto_(p.mensagem).slice(0,700);if(!familia)throw new Error('Cadastro familiar inválido.');if(msg.length<3)throw new Error('Digite a mensagem.');var cfg=mensagemIndividualV1ConfigOneSignal_(),alvos=mensagemFamiliaV1Alvos_(contexto,familia,cfg);if(!alvos.length)return {ok:true,enviado:false,semAparelho:true,familiaId:familia,message:'A família '+familia+' ainda não possui aparelho Push apto e vinculado.'};var input={titulo:'Portal TACS — Aviso para família '+familia,mensagem:msg,tipo:'MENSAGEM_FAMILIA',referencia:'FAMILIA_'+familia,evento:id},prep=notificacoesAreaV1PrepararComprovantes_(contexto,input,alvos),resp;try{resp=UrlFetchApp.fetchAll(prep.map(function(item){return {url:TACS_NOTIFICACOES_AREA_V1.ENDPOINT,method:'post',contentType:'application/json',payload:JSON.stringify(notificacoesAreaV1PayloadIndividual_(cfg.appId,contexto,input,item)),headers:{Authorization:'Key '+cfg.apiKey},muteHttpExceptions:true}}))}catch(e){notificacoesAreaV1MarcarFalhaLote_(prep,e);throw new Error('A conexão com o serviço Push falhou.')}var resumo=notificacoesAreaV1AplicarRespostasEnvio_(prep,resp);notificacoesAreaV1Auditar_(contexto,acesso,input,resumo.primeiroId||'',alvos.length,resumo.encaminhados?'ENCAMINHADA_FAMILIA':'ERRO_ENVIO_FAMILIA');if(!resumo.encaminhados)throw new Error('O serviço Push não aceitou a mensagem para nenhum aparelho desta família.');return {ok:true,enviado:true,eventoId:id,familiaId:familia,aparelhos:alvos.length,encaminhadas:resumo.encaminhados,falhas:resumo.falhas||0}}
function mensagemFamiliaV1Status_(p,contexto){var evento=mensagemFamiliaV1Texto_(p.eventoId),familia=mensagemIndividualV1NormalizarFamilia_(p.familiaId||''),ref='FAMILIA_'+familia;if(!familia||!evento)throw new Error('Envio familiar inválido.');var ss=tacsTerritorioV1Planilha_(),rec=ss.getSheetByName(TACS_NOTIFICACOES_AREA_V1.RECEIPT_SHEET),open=ss.getSheetByName(TACS_NOTIFICACOES_AREA_V1.OPEN_SHEET),total=0,enc=0,exib=0,conf=0,ab=0;if(rec&&rec.getLastRow()>1)rec.getRange(2,1,rec.getLastRow()-1,TACS_NOTIFICACOES_AREA_V1.RECEIPT_HEADERS.length).getDisplayValues().forEach(function(row){if(row[0]!==evento||mensagemFamiliaV1Texto_(row[1]).toUpperCase()!==contexto.areaId||row[3]!==ref)return;total++;if(row[13])enc++;if(row[14])exib++;if(row[15])conf++});if(open&&open.getLastRow()>1)open.getRange(2,1,open.getLastRow()-1,TACS_NOTIFICACOES_AREA_V1.OPEN_HEADERS.length).getDisplayValues().forEach(function(row){if(row[0]===evento&&mensagemFamiliaV1Texto_(row[1]).toUpperCase()===contexto.areaId&&row[3]===ref)ab++});return {ok:true,eventoId:evento,familiaId:familia,aparelhos:total,encaminhadas:enc,exibidas:exib,abertas:ab,confirmadas:conf}}
