/** Portal TACS — Mensagem geral por cadastro familiar V1.0.0 */
var TACS_MENSAGEM_FAMILIA_V1=Object.freeze({VERSAO:'1.0.0',RESULT_PREFIX:'tacs_msg_familia_v1_result_',RESULT_SECONDS:300});
var mensagemFamiliaV1DoGetAnterior_,mensagemFamiliaV1DoPostAnterior_;
(function(){if(typeof doGet==='function'){mensagemFamiliaV1DoGetAnterior_=doGet;doGet=function(e){return mensagemFamiliaV1Get_(e)||mensagemFamiliaV1DoGetAnterior_(e)}}if(typeof doPost==='function'){mensagemFamiliaV1DoPostAnterior_=doPost;doPost=function(e){return mensagemFamiliaV1Post_(e)||mensagemFamiliaV1DoPostAnterior_(e)}}})();
function mensagemFamiliaV1Texto_(v){return String(v==null?'':v).trim()}
function mensagemFamiliaV1Json_(obj,cb){var s=JSON.stringify(obj),c=mensagemFamiliaV1Texto_(cb);if(c&&/^[A-Za-z_$][A-Za-z0-9_$\.]{0,120}$/.test(c))return ContentService.createTextOutput(c+'('+s+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(s).setMimeType(ContentService.MimeType.JSON)}
function mensagemFamiliaV1Guardar_(id,r){CacheService.getScriptCache().put(TACS_MENSAGEM_FAMILIA_V1.RESULT_PREFIX+id,JSON.stringify(r),TACS_MENSAGEM_FAMILIA_V1.RESULT_SECONDS)}
function mensagemFamiliaV1Ler_(id){var s=CacheService.getScriptCache().get(TACS_MENSAGEM_FAMILIA_V1.RESULT_PREFIX+id);if(!s)return null;try{return JSON.parse(s)}catch(e){return null}}
function mensagemFamiliaV1Get_(e){var p=e&&e.parameter?e.parameter:{};if(mensagemFamiliaV1Texto_(p.action).toLowerCase()!=='admin_mensagem_familia_result')return null;var id=mensagemFamiliaV1Texto_(p.requestId);if(!/^[A-Za-z0-9_-]{8,160}$/.test(id))return mensagemFamiliaV1Json_({ok:false,message:'Identificador inválido.'},p.callback);var r=mensagemFamiliaV1Ler_(id);return mensagemFamiliaV1Json_(r?{ok:true,pendente:false,result:r}:{ok:true,pendente:true},p.callback)}
function mensagemFamiliaV1Post_(e){var p=e&&e.parameter?e.parameter:{};if(mensagemFamiliaV1Texto_(p.action).toLowerCase()!=='admin_mensagem_familia_enviar')return null;var id=mensagemFamiliaV1Texto_(p.requestId),r;try{if(!/^[A-Za-z0-9_-]{8,160}$/.test(id))throw new Error('Identificador inválido.');var sess=mensagemIndividualV1Contexto_(p,true);r=mensagemFamiliaV1Enviar_(p,sess.contexto,sess.acesso,id)}catch(err){r={ok:false,message:err&&err.message?err.message:String(err)}}if(/^[A-Za-z0-9_-]{8,160}$/.test(id))mensagemFamiliaV1Guardar_(id,r);return mensagemFamiliaV1ResponderPost_(id,r)}
function mensagemFamiliaV1ResponderPost_(id,r){var html='<!doctype html><meta charset="utf-8"><script>try{parent.postMessage('+JSON.stringify({requestId:id,result:r})+',"*")}catch(e){}<\/script>';return HtmlService.createHtmlOutput(html).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function mensagemFamiliaV1Enviar_(p,contexto,acesso,id){var familia=mensagemIndividualV1NormalizarFamilia_(p.familiaId||p.familia||'');if(!familia)throw new Error('Cadastro familiar inválido.');var mensagem=mensagemFamiliaV1Texto_(p.mensagem).slice(0,700);if(mensagem.length<3)throw new Error('Digite a mensagem.');var cfg=mensagemIndividualV1ConfigOneSignal_(),todos=notificacoesAreaV1AlvosAtivos_(cfg.appId,cfg.apiKey,contexto,notificacoesAreaV1QuantidadeAreas_()),mapa=mensagemIndividualV1MapaFamilias_(tacsTerritorioV1Planilha_(),contexto.areaId),vistos={};var alvos=todos.filter(function(a){var sid=mensagemFamiliaV1Texto_(a&&a.subscriptionId).toLowerCase();if(!sid||vistos[sid]||mapa[sid]!==familia)return false;vistos[sid]=true;return true}).map(function(a){return {subscriptionId:a.subscriptionId,idPortal:'FAMILIA_'+familia,tipoAparelho:a.tipoAparelho,navegador:a.navegador,sistema:a.sistema}});if(!alvos.length)return {ok:true,enviado:false,semAparelho:true,familiaId:familia,message:'A família '+familia+' ainda não possui aparelho Push apto e vinculado.'};var input={titulo:'Portal TACS — Aviso para família '+familia,mensagem:mensagem,tipo:'MENSAGEM_FAMILIA',referencia:'FAMILIA_'+familia,evento:id},prep=notificacoesAreaV1PrepararComprovantes_(contexto,input,alvos),resp;try{resp=UrlFetchApp.fetchAll(prep.map(function(item){return {url:TACS_NOTIFICACOES_AREA_V1.ENDPOINT,method:'post',contentType:'application/json',payload:JSON.stringify(notificacoesAreaV1PayloadIndividual_(cfg.appId,contexto,input,item)),headers:{Authorization:'Key '+cfg.apiKey},muteHttpExceptions:true}}))}catch(e){notificacoesAreaV1MarcarFalhaLote_(prep,e);throw new Error('A conexão com o serviço Push falhou.')}var resumo=notificacoesAreaV1AplicarRespostasEnvio_(prep,resp);notificacoesAreaV1Auditar_(contexto,acesso,input,resumo.primeiroId||'',alvos.length,resumo.encaminhados?'ENCAMINHADA_FAMILIA':'ERRO_ENVIO_FAMILIA');if(!resumo.encaminhados)throw new Error('O serviço Push não aceitou a mensagem para nenhum aparelho desta família.');return {ok:true,enviado:true,familiaId:familia,aparelhos:alvos.length,encaminhadas:resumo.encaminhados,falhas:resumo.falhas||0,eventoId:id}}
